export type Language = "cpp" | "java" | "python";

export type Lesson = {
  id: string;
  number: number;
  week: number;
  weekTitle: string;
  title: string;
  concept: string;
  focus: string;
  practice: string;
  practiceUrl: string;
  resource: string;
  resourceUrl: string;
  edgeCase: string;
  topicIntro: string;
  videoUrl: string;
  videoTitle: string;
  articleUrl: string;
  articleTitle: string;
};

type DaySeed = Omit<Lesson, "id" | "number" | "week" | "weekTitle">;
type WeekSeed = { title: string; days: DaySeed[] };

const gfg = "https://www.geeksforgeeks.org";
const mit = "https://ocw.mit.edu/courses/6-006-introduction-to-algorithms-fall-2011/";
const visualgo = "https://visualgo.net/en";
const a2z = "https://takeuforward.org/strivers-a2z-dsa-course/strivers-a2z-dsa-course-sheet-2/";
const hr = "https://www.hackerrank.com/domains/data-structures";
const leet = "https://leetcode.com/problemset/";
const cses = "https://cses.fi/problemset/";

const weeks: WeekSeed[] = [
  { title: "Cost & Arrays", days: [
    {
      title: "How algorithms grow",
      concept: "Compare constant, logarithmic, linear, and quadratic growth on real input sizes.",
      focus: "Write a max scan and a nested pair check; count their operations.",
      practice: "Simple Array Sum",
      practiceUrl: "https://www.hackerrank.com/challenges/simple-array-sum/problem",
      resource: "Big-O foundations",
      resourceUrl: mit,
      edgeCase: "What changes when the array is empty or has one item?",
      topicIntro: "Big-O notation is the language we use to describe how slow or fast an algorithm gets as input grows. Think of it like this: if cooking for 10 people takes 10 minutes, does cooking for 100 people take 100 minutes (linear) or 10,000 minutes (quadratic)? We use Big-O to classify this without worrying about exact steps.",
      videoUrl: "https://www.youtube.com/watch?v=0IAPZzGSbME",
      videoTitle: "Big O Notation — Abdul Bari",
      articleUrl: "https://www.geeksforgeeks.org/analysis-of-algorithms-big-o-analysis/",
      articleTitle: "Big-O Analysis — GeeksforGeeks",
    },
    {
      title: "Arrays in memory",
      concept: "Contiguous memory explains fast indexing and expensive middle insertion.",
      focus: "Trace access, append, insertion, and deletion on paper.",
      practice: "Arrays: DS",
      practiceUrl: "https://www.hackerrank.com/challenges/arrays-ds/problem",
      resource: "Array operations",
      resourceUrl: visualgo,
      edgeCase: "Which elements shift after an insertion at index zero?",
      topicIntro: "An array is a row of numbered boxes in memory — you can jump directly to box #5 in one step (O(1)), but inserting a new box in the middle means shifting every box to the right (O(n)). Understanding this physical layout explains why some operations are fast and others slow.",
      videoUrl: "https://www.youtube.com/watch?v=QJNwK2uJyGs",
      videoTitle: "Arrays — mycodeschool",
      articleUrl: "https://www.geeksforgeeks.org/array-data-structure/",
      articleTitle: "Array Data Structure — GeeksforGeeks",
    },
    {
      title: "2D grids",
      concept: "A matrix is a collection of row and column indices.",
      focus: "Write nested loops that visit every cell of a 3×3 grid.",
      practice: "2D Array: DS",
      practiceUrl: "https://www.hackerrank.com/challenges/2d-array/problem",
      resource: "Array visualizer",
      resourceUrl: visualgo,
      edgeCase: "How do you avoid walking beyond the last row or column?",
      topicIntro: "A 2D array is just an array of arrays — picture a spreadsheet. Row 0, Column 3 means go to the 0th row, then jump to the 3rd column. In code, arr[row][col] accesses any cell directly. Nested loops let you visit every cell systematically.",
      videoUrl: "https://www.youtube.com/watch?v=iqt-ropMXGE",
      videoTitle: "2D Arrays — CS Dojo",
      articleUrl: "https://www.geeksforgeeks.org/multidimensional-arrays-in-c/",
      articleTitle: "2D Arrays — GeeksforGeeks",
    },
    {
      title: "Rotation by k",
      concept: "Circular movement repeats after n positions, so k mod n matters.",
      focus: "Map each old index to its new index before writing code.",
      practice: "Left Rotation",
      practiceUrl: "https://www.hackerrank.com/challenges/array-left-rotation/problem",
      resource: "Arrays basics",
      resourceUrl: a2z,
      edgeCase: "Test k = 0, k = n, and k greater than n.",
      topicIntro: "Rotating an array shifts all elements left or right by k positions, wrapping around at the edges — like rotating a circular list. The key insight: rotating by n (the array length) returns you to the start, so we only need to rotate by k mod n steps.",
      videoUrl: "https://www.youtube.com/watch?v=wvcQg43_V8U",
      videoTitle: "Array Rotation — take U forward",
      articleUrl: "https://www.geeksforgeeks.org/array-rotation/",
      articleTitle: "Array Rotation — GeeksforGeeks",
    },
    {
      title: "Prefix sums",
      concept: "Precompute cumulative sums to answer range queries quickly.",
      focus: "Build an inclusive prefix array and answer two ranges by subtraction.",
      practice: "Running Sum of 1D Array",
      practiceUrl: "https://leetcode.com/problems/running-sum-of-1d-array/",
      resource: "Prefix-sum pattern",
      resourceUrl: a2z,
      edgeCase: "How does a query starting at index zero work?",
      topicIntro: "If someone asks 'what is the sum from index 3 to 7?' naively you add 5 numbers each time. Prefix sums precompute cumulative totals so any range query answers in O(1) with a single subtraction. It trades a little memory for massive speed on repeated queries.",
      videoUrl: "https://www.youtube.com/watch?v=pVS3yhlzrlQ",
      videoTitle: "Prefix Sum Array — take U forward",
      articleUrl: "https://www.geeksforgeeks.org/prefix-sum-array-implementation-applications-competitive-programming/",
      articleTitle: "Prefix Sum Array — GeeksforGeeks",
    },
    {
      title: "Arrays review",
      concept: "Retrieval beats rereading: explain costs and index mappings from memory.",
      focus: "Re-solve one array miss and write one array invariant.",
      practice: "Array revision",
      practiceUrl: hr,
      resource: "HackerRank arrays",
      resourceUrl: hr,
      edgeCase: "Which array operation surprised you most this week?",
      topicIntro: "This is your consolidation day — no new concepts, just reinforcement. The best way to learn is to close your notes and try to re-explain everything from this week. If you can't explain it simply, you don't know it well enough yet.",
      videoUrl: "https://www.youtube.com/watch?v=RBSGKlAvoiM",
      videoTitle: "Arrays Review — William Fiset",
      articleUrl: "https://www.geeksforgeeks.org/array-data-structure/",
      articleTitle: "Array Cheatsheet — GeeksforGeeks",
    },
  ] },
  { title: "Strings & Hashing", days: [
    {
      title: "Strings as arrays",
      concept: "Strings are sequences; scanning and building them has a measurable cost.",
      focus: "Trace a palindrome check using two pointers.",
      practice: "Valid Palindrome",
      practiceUrl: "https://leetcode.com/problems/valid-palindrome/",
      resource: "String basics",
      resourceUrl: a2z,
      edgeCase: "Ignore punctuation and casing deliberately.",
      topicIntro: "A string is really just an array of characters. 'hello' is ['h','e','l','l','o'] in memory. The two-pointer technique places one pointer at the start and one at the end, moving inward — this is how you check palindromes in O(n) time without creating a reversed copy.",
      videoUrl: "https://www.youtube.com/watch?v=jER_hg9hMTQ",
      videoTitle: "Two Pointer Technique — NeetCode",
      articleUrl: "https://www.geeksforgeeks.org/two-pointer-technique/",
      articleTitle: "Two Pointer Technique — GeeksforGeeks",
    },
    {
      title: "Frequency maps",
      concept: "A hash map stores a compact state for each key.",
      focus: "Hand-build a frequency map, then implement count-or-increment.",
      practice: "Sparse Arrays",
      practiceUrl: "https://www.hackerrank.com/challenges/sparse-arrays/problem",
      resource: "Hashing basics",
      resourceUrl: a2z,
      edgeCase: "What should a missing key return?",
      topicIntro: "A hash map is like a phone book — given a name (key), it instantly looks up the number (value) in O(1). For frequency counting, the key is a character or word, and the value is how many times it appeared. This turns an O(n²) repeated scan into a single O(n) pass.",
      videoUrl: "https://www.youtube.com/watch?v=shs0KM3wKv8",
      videoTitle: "Hashing — Abdul Bari",
      articleUrl: "https://www.geeksforgeeks.org/hashing-data-structure/",
      articleTitle: "Hashing Data Structure — GeeksforGeeks",
    },
    {
      title: "Anagrams",
      concept: "Two strings are anagrams when their frequency distributions match.",
      focus: "Compare a sorted solution with a frequency-map solution.",
      practice: "Valid Anagram",
      practiceUrl: "https://leetcode.com/problems/valid-anagram/",
      resource: "Hashing patterns",
      resourceUrl: a2z,
      edgeCase: "What happens with unequal lengths?",
      topicIntro: "Two words are anagrams if they use the exact same letters in different orders — 'listen' and 'silent' for example. You detect this by counting letter frequencies in both strings and comparing. If all counts match, they're anagrams.",
      videoUrl: "https://www.youtube.com/watch?v=9UtInBqnCgA",
      videoTitle: "Valid Anagram — NeetCode",
      articleUrl: "https://www.geeksforgeeks.org/check-whether-two-strings-are-anagram-of-each-other/",
      articleTitle: "Check if Anagram — GeeksforGeeks",
    },
    {
      title: "Two sum",
      concept: "Store what you need for the future while scanning only once.",
      focus: "State the complement before looking it up.",
      practice: "Two Sum",
      practiceUrl: "https://leetcode.com/problems/two-sum/",
      resource: "Hash-map patterns",
      resourceUrl: a2z,
      edgeCase: "Never reuse the same element twice.",
      topicIntro: "Two Sum asks: which two numbers add up to a target? The brute-force checks every pair — O(n²). The hash map trick: as you scan, store each number. For each new number, check if (target - number) already exists. This finds the answer in one pass — O(n).",
      videoUrl: "https://www.youtube.com/watch?v=KLlXCFG5TnA",
      videoTitle: "Two Sum — NeetCode",
      articleUrl: "https://www.geeksforgeeks.org/given-an-array-a-and-a-number-x-check-for-pair-in-a-with-sum-as-x/",
      articleTitle: "Two Sum Pattern — GeeksforGeeks",
    },
    {
      title: "Longest subarray",
      concept: "A prefix state can turn a quadratic search into a linear one.",
      focus: "Trace prefix sum values and their earliest positions.",
      practice: "Longest Subarray with Sum K",
      practiceUrl: a2z,
      resource: "Prefix hashing",
      resourceUrl: a2z,
      edgeCase: "Keep the first occurrence of each prefix total.",
      topicIntro: "Finding the longest subarray with sum K combines prefix sums with hashing. You store the earliest index where each prefix sum value was first seen. When prefix[j] - prefix[i] = K, the subarray from i+1 to j has sum K. Storing the first occurrence maximizes the length.",
      videoUrl: "https://www.youtube.com/watch?v=frf7qxiN2qU",
      videoTitle: "Longest Subarray with Sum K — take U forward",
      articleUrl: "https://www.geeksforgeeks.org/longest-sub-array-sum-k/",
      articleTitle: "Longest Subarray with Sum K — GeeksforGeeks",
    },
    {
      title: "Hashing review",
      concept: "Choose maps when a repeated scan can become a lookup.",
      focus: "Re-solve an anagram or two-sum problem without notes.",
      practice: "Hash table practice",
      practiceUrl: hr,
      resource: "Hash table visualizer",
      resourceUrl: visualgo,
      edgeCase: "Name the key and the value before coding.",
      topicIntro: "The hash map pattern is one of the most powerful DSA tools. Before using one, always ask: 'what is the key, and what value do I want to store?' Getting that right is the whole trick. Today you consolidate by re-solving problems without notes.",
      videoUrl: "https://www.youtube.com/watch?v=shs0KM3wKv8",
      videoTitle: "Hashing Deep Dive — Abdul Bari",
      articleUrl: "https://visualgo.net/en/hashtable",
      articleTitle: "Hash Table Visualizer — VisuAlgo",
    },
  ] },
  { title: "Sorting & Search", days: [
    {
      title: "Selection & bubble sort",
      concept: "An invariant describes the part that is already sorted.",
      focus: "Trace both sorts on five numbers and count comparisons.",
      practice: "Selection Sort",
      practiceUrl: a2z,
      resource: "Sorting visualizer",
      resourceUrl: visualgo,
      edgeCase: "What happens when the list is already sorted?",
      topicIntro: "Selection sort finds the minimum element and puts it first, then the next minimum, and so on. Bubble sort repeatedly swaps adjacent out-of-order elements. Both are O(n²) — slow for large arrays but great to understand. The key is the invariant: after k passes, the first k elements are sorted.",
      videoUrl: "https://www.youtube.com/watch?v=xWBP4lzkoyM",
      videoTitle: "Selection Sort & Bubble Sort — Abdul Bari",
      articleUrl: "https://www.geeksforgeeks.org/selection-sort/",
      articleTitle: "Selection Sort — GeeksforGeeks",
    },
    {
      title: "Insertion sort",
      concept: "A sorted prefix grows one item at a time.",
      focus: "Move an item left until it reaches its valid position.",
      practice: "Insertion Sort Part 1",
      practiceUrl: "https://www.hackerrank.com/challenges/insertionsort1/problem",
      resource: "Sorting foundations",
      resourceUrl: mit,
      edgeCase: "Stop shifting as soon as the previous value is smaller.",
      topicIntro: "Insertion sort works like sorting a hand of playing cards — take one card at a time and insert it into the correct position among already-sorted cards. It's O(n²) worst case but O(n) on nearly-sorted data. That's why databases use it for small datasets.",
      videoUrl: "https://www.youtube.com/watch?v=i-SKeOcBwko",
      videoTitle: "Insertion Sort — Abdul Bari",
      articleUrl: "https://www.geeksforgeeks.org/insertion-sort/",
      articleTitle: "Insertion Sort — GeeksforGeeks",
    },
    {
      title: "Merge sort",
      concept: "Divide, solve smaller copies, and merge in sorted order.",
      focus: "Draw the recursion tree for eight values.",
      practice: "Merge Sort",
      practiceUrl: a2z,
      resource: "Merge-sort lesson",
      resourceUrl: mit,
      edgeCase: "When equal values appear, choose consistently.",
      topicIntro: "Merge sort is divide-and-conquer: split the array in half, sort each half recursively, then merge the two sorted halves. It runs in O(n log n) always — never degrades. The merge step is the key: scan both halves with two pointers, always picking the smaller element.",
      videoUrl: "https://www.youtube.com/watch?v=TzeBrDU-JaY",
      videoTitle: "Merge Sort — Abdul Bari",
      articleUrl: "https://www.geeksforgeeks.org/merge-sort/",
      articleTitle: "Merge Sort — GeeksforGeeks",
    },
    {
      title: "Binary search",
      concept: "Binary search needs a monotonic condition and clear boundaries.",
      focus: "Write low, high, and mid updates on paper first.",
      practice: "Binary Search",
      practiceUrl: "https://leetcode.com/problems/binary-search/",
      resource: "Binary search patterns",
      resourceUrl: a2z,
      edgeCase: "Test empty, one-item, and not-found arrays.",
      topicIntro: "Binary search is how you search a phone book — instead of checking every name, open to the middle, decide if the target is left or right, and discard half. Each step halves the search space, giving O(log n). The array MUST be sorted. Without that, binary search gives wrong answers.",
      videoUrl: "https://www.youtube.com/watch?v=f6UU7V3szVw",
      videoTitle: "Binary Search — take U forward",
      articleUrl: "https://www.geeksforgeeks.org/binary-search/",
      articleTitle: "Binary Search — GeeksforGeeks",
    },
    {
      title: "Boundary search",
      concept: "Search can locate the first true or last true condition.",
      focus: "State the answer range and preserve it through each loop.",
      practice: "First and Last Position",
      practiceUrl: "https://leetcode.com/problems/find-first-and-last-position-of-element-in-sorted-array/",
      resource: "Binary-search boundaries",
      resourceUrl: a2z,
      edgeCase: "Avoid an infinite loop when mid equals a boundary.",
      topicIntro: "Binary search can find the FIRST or LAST position where a condition becomes true. Imagine a yes/no boundary: 'is this element ≥ target?' Binary search finds exactly where the answer flips from No to Yes. This pattern unlocks a whole class of search problems beyond simple lookup.",
      videoUrl: "https://www.youtube.com/watch?v=0H5s7eTHc90",
      videoTitle: "Binary Search on Answers — NeetCode",
      articleUrl: "https://www.geeksforgeeks.org/find-first-and-last-positions-of-an-element-in-a-sorted-array/",
      articleTitle: "First and Last Position — GeeksforGeeks",
    },
    {
      title: "Sort & search review",
      concept: "The proof is in the invariant, not in memorized code.",
      focus: "Re-solve binary search and explain why the range shrinks.",
      practice: "Distinct Numbers",
      practiceUrl: "https://cses.fi/problemset/task/1621",
      resource: "CSES sorting",
      resourceUrl: cses,
      edgeCase: "What condition is monotonic in your solution?",
      topicIntro: "This week you covered the most important foundational algorithms — sorting and searching. These aren't just homework topics; they're inside every database, OS, and search engine. Today you solidify them by re-solving from memory and explaining the invariants.",
      videoUrl: "https://www.youtube.com/watch?v=HGK_5-RoF_I",
      videoTitle: "Sorting Algorithms Review — Abdul Bari",
      articleUrl: "https://www.geeksforgeeks.org/sorting-algorithms/",
      articleTitle: "Sorting Algorithms Overview — GeeksforGeeks",
    },
  ] },
  { title: "Linear Structures", days: [
    {
      title: "Linked-list anatomy",
      concept: "Each node stores a value and a connection to the next node.",
      focus: "Draw insert-at-head and insert-at-tail pointer changes.",
      practice: "Print Linked List",
      practiceUrl: "https://www.hackerrank.com/challenges/print-the-elements-of-a-linked-list/problem",
      resource: "Linked-list visualizer",
      resourceUrl: visualgo,
      edgeCase: "What does head mean for an empty list?",
      topicIntro: "A linked list is a chain of nodes — each node holds a value and a pointer to the next node. Unlike arrays, nodes don't have to be adjacent in memory. This makes insertion at the head O(1) (redirect the head pointer), but random access O(n) since you must walk the chain.",
      videoUrl: "https://www.youtube.com/watch?v=njTh_OwMljA",
      videoTitle: "Linked Lists — mycodeschool",
      articleUrl: "https://www.geeksforgeeks.org/data-structures/linked-list/",
      articleTitle: "Linked List — GeeksforGeeks",
    },
    {
      title: "List insertion",
      concept: "Pointer order matters: preserve the next node before rewiring.",
      focus: "Implement head and tail insertion without losing a node.",
      practice: "Insert a Node at the Tail",
      practiceUrl: "https://www.hackerrank.com/challenges/insert-a-node-at-the-tail-of-a-linked-list/problem",
      resource: "Linked-list operations",
      resourceUrl: a2z,
      edgeCase: "Update tail when the old list was empty.",
      topicIntro: "Inserting into a linked list is about carefully redirecting pointers. The golden rule: never lose your reference to the next node before you've saved it. Always: (1) set the new node's next, (2) update the previous node's next. The order matters — get it wrong and you break the chain.",
      videoUrl: "https://www.youtube.com/watch?v=o5wJkJW3fCs",
      videoTitle: "Linked List Insertion — mycodeschool",
      articleUrl: "https://www.geeksforgeeks.org/linked-list-set-2-inserting-a-node/",
      articleTitle: "Inserting Into Linked List — GeeksforGeeks",
    },
    {
      title: "Stacks",
      concept: "Last-in, first-out is a contract, not just a container.",
      focus: "Trace push and pop operations with a top pointer.",
      practice: "Valid Parentheses",
      practiceUrl: "https://leetcode.com/problems/valid-parentheses/",
      resource: "Stack visualizer",
      resourceUrl: visualgo,
      edgeCase: "A closing bracket cannot pop an empty stack.",
      topicIntro: "A stack is like a stack of plates — you can only add or remove from the top. LIFO (Last In, First Out) means the most recently added item leaves first. Stacks are perfect for bracket matching, function call tracking, and undo operations. Every recursive call uses the system's call stack.",
      videoUrl: "https://www.youtube.com/watch?v=GYptUgnIM_I",
      videoTitle: "Stack Data Structure — take U forward",
      articleUrl: "https://www.geeksforgeeks.org/stack-data-structure-introduction-program/",
      articleTitle: "Stack Data Structure — GeeksforGeeks",
    },
    {
      title: "Queues",
      concept: "First-in, first-out supports ordered processing.",
      focus: "Trace a circular queue using front and rear indices.",
      practice: "Queue using Two Stacks",
      practiceUrl: "https://leetcode.com/problems/implement-queue-using-stacks/",
      resource: "Queue visualizer",
      resourceUrl: visualgo,
      edgeCase: "Distinguish an empty queue from a full circular queue.",
      topicIntro: "A queue is like a checkout line — first person in is first person served. FIFO (First In, First Out). BFS uses a queue to process nodes level by level. A circular queue reuses array space by wrapping the rear pointer back to index 0 when it reaches the end.",
      videoUrl: "https://www.youtube.com/watch?v=zp6pBNbUB2U",
      videoTitle: "Queue Data Structure — take U forward",
      articleUrl: "https://www.geeksforgeeks.org/queue-data-structure/",
      articleTitle: "Queue Data Structure — GeeksforGeeks",
    },
    {
      title: "Monotonic stacks",
      concept: "Maintain a stack with a useful order to avoid repeat work.",
      focus: "Trace next-greater-element pops one by one.",
      practice: "Next Greater Element I",
      practiceUrl: "https://leetcode.com/problems/next-greater-element-i/",
      resource: "Stack patterns",
      resourceUrl: a2z,
      edgeCase: "What remains on the stack at the end?",
      topicIntro: "A monotonic stack stays in sorted order (always increasing or always decreasing). It solves 'next greater element' problems in O(n): scan left to right, maintaining a stack of elements without answers yet. When a larger element arrives, it's the answer for everything it pops off the stack.",
      videoUrl: "https://www.youtube.com/watch?v=Dq_ObZwTY_Q",
      videoTitle: "Next Greater Element — NeetCode",
      articleUrl: "https://www.geeksforgeeks.org/next-greater-element/",
      articleTitle: "Next Greater Element — GeeksforGeeks",
    },
    {
      title: "Linear review",
      concept: "Every structure is defined by the invariant it preserves.",
      focus: "Re-implement valid parentheses with no reference.",
      practice: "Stack and queue revision",
      practiceUrl: hr,
      resource: "Linear structures",
      resourceUrl: visualgo,
      edgeCase: "Can you say why each operation is O(1)?",
      topicIntro: "Stacks and queues seem simple but underpin huge systems: queues handle job scheduling in your OS, stacks trace function calls, monotonic stacks compress range queries to linear time. Lock in the reasoning today — not the code, but the 'why'.",
      videoUrl: "https://www.youtube.com/watch?v=RBSGKlAvoiM",
      videoTitle: "Stacks & Queues Review — William Fiset",
      articleUrl: "https://visualgo.net/en/list",
      articleTitle: "Linked List & Stack Visualizer — VisuAlgo",
    },
  ] },
  { title: "Recursion & Bits", days: [
    {
      title: "Base cases",
      concept: "A recursive call must reduce input and reach a visible base case.",
      focus: "Write factorial, sum, and reverse-array calls on a call stack.",
      practice: "Recursive Digit Sum",
      practiceUrl: "https://www.hackerrank.com/challenges/recursive-digit-sum/problem",
      resource: "Recursion basics",
      resourceUrl: a2z,
      edgeCase: "Which input stops the recursion?",
      topicIntro: "Recursion is a function that calls itself with a smaller input. Every recursive solution needs: (1) a base case that stops the recursion, and (2) a recursive call that makes the problem smaller. Without a base case, it runs forever. Think of it as: 'solve the tiny version, then build up.'",
      videoUrl: "https://www.youtube.com/watch?v=M2uO2nMT0Bk",
      videoTitle: "Recursion Basics — Abdul Bari",
      articleUrl: "https://www.geeksforgeeks.org/recursion/",
      articleTitle: "Recursion — GeeksforGeeks",
    },
    {
      title: "Subsequences",
      concept: "Each element is either chosen or not chosen, giving 2ⁿ possibilities.",
      focus: "Draw the choice tree for three elements.",
      practice: "Subsets",
      practiceUrl: "https://leetcode.com/problems/subsets/",
      resource: "Backtracking",
      resourceUrl: a2z,
      edgeCase: "When do you record a completed choice?",
      topicIntro: "A subsequence keeps the relative order of elements but can skip any subset of them. For n elements, there are 2ⁿ possible subsets (each element is either in or out). Recursion handles this naturally with a binary tree of choices — include this element, or skip it.",
      videoUrl: "https://www.youtube.com/watch?v=45GCRpSWHoA",
      videoTitle: "Subsets — take U forward",
      articleUrl: "https://www.geeksforgeeks.org/backtracking-to-find-all-subsets/",
      articleTitle: "Generate All Subsets — GeeksforGeeks",
    },
    {
      title: "Permutations",
      concept: "Permutation generation places one unused choice at each position.",
      focus: "Trace swap, recurse, and undo.",
      practice: "Permutations",
      practiceUrl: "https://leetcode.com/problems/permutations/",
      resource: "Recursion trees",
      resourceUrl: mit,
      edgeCase: "Undo every mutation before the next branch.",
      topicIntro: "A permutation is every possible ordering of a set of elements. For [1,2,3] there are 3! = 6 permutations. The algorithm: place each unused element in the current position, recurse to fill the rest, then undo (backtrack) your choice. The 'undo' step is critical — it restores state so other branches work correctly.",
      videoUrl: "https://www.youtube.com/watch?v=YK78FU5Ffjw",
      videoTitle: "Permutations — take U forward",
      articleUrl: "https://www.geeksforgeeks.org/write-a-c-program-to-print-all-permutations-of-a-given-string/",
      articleTitle: "Generate Permutations — GeeksforGeeks",
    },
    {
      title: "Bit operations",
      concept: "Binary representation makes some state compact and fast to inspect.",
      focus: "Use AND, OR, XOR, shifts, and masks on small values.",
      practice: "Number of 1 Bits",
      practiceUrl: "https://leetcode.com/problems/number-of-1-bits/",
      resource: "Bit manipulation",
      resourceUrl: a2z,
      edgeCase: "Use parentheses around shifted expressions.",
      topicIntro: "Every integer is stored as bits (0s and 1s) in memory. Bit operations (AND, OR, XOR, left shift, right shift) let you manipulate individual bits directly — often much faster than arithmetic. Key uses: check if even (n & 1 == 0), multiply by 2 (n << 1), toggle individual flags.",
      videoUrl: "https://www.youtube.com/watch?v=NLKQEOgBAnw",
      videoTitle: "Bit Manipulation — take U forward",
      articleUrl: "https://www.geeksforgeeks.org/bits-manipulation-important-tactics/",
      articleTitle: "Bit Manipulation Tricks — GeeksforGeeks",
    },
    {
      title: "Bitmask subsets",
      concept: "Every number from 0 to 2ⁿ−1 can represent a subset.",
      focus: "Map set bits to selected elements.",
      practice: "Bit Strings",
      practiceUrl: "https://cses.fi/problemset/task/1617",
      resource: "Bitmasking",
      resourceUrl: a2z,
      edgeCase: "Why does bit i represent element i?",
      topicIntro: "A bitmask uses a single integer to represent a set. If bit i is 1, element i is in the set. For 3 elements, we have 2³=8 possible masks (000 to 111), each a unique subset. This technique is used in DP over subsets and state compression problems.",
      videoUrl: "https://www.youtube.com/watch?v=4cShRHbFfhg",
      videoTitle: "Bitmask DP — take U forward",
      articleUrl: "https://www.geeksforgeeks.org/bitmasking-and-dynamic-programming-set-1-count-ways-to-assign-unique-cap-to-every-person/",
      articleTitle: "Bitmask + DP — GeeksforGeeks",
    },
    {
      title: "Recursion review",
      concept: "Correct recursive code explains its smallest case and its smaller call.",
      focus: "Re-solve subsets and narrate the recursion tree.",
      practice: "Recursion revision",
      practiceUrl: a2z,
      resource: "Recursion visualizer",
      resourceUrl: visualgo,
      edgeCase: "What state must be restored after a call?",
      topicIntro: "Recursion and backtracking are foundational for trees, graphs, and DP. Today you review by narrating solutions out loud — explaining base cases, recursive choices, and what gets undone. This is exactly the practice that separates people who 'know' algorithms from those who can actually use them.",
      videoUrl: "https://www.youtube.com/watch?v=M2uO2nMT0Bk",
      videoTitle: "Recursion Review — Abdul Bari",
      articleUrl: "https://www.geeksforgeeks.org/recursion-practice-problems-solutions/",
      articleTitle: "Recursion Practice Problems — GeeksforGeeks",
    },
  ] },
  { title: "Trees & Heaps", days: [
    {
      title: "Tree traversals",
      concept: "Traversal order tells you when a node is visited relative to children.",
      focus: "Write pre-, in-, and post-order for one drawn tree.",
      practice: "Binary Tree Preorder Traversal",
      practiceUrl: "https://leetcode.com/problems/binary-tree-preorder-traversal/",
      resource: "Tree visualizer",
      resourceUrl: visualgo,
      edgeCase: "A null child is a base case.",
      topicIntro: "A binary tree is a hierarchy where each node has at most two children. There are three ways to visit all nodes: pre-order (node → left → right), in-order (left → node → right), post-order (left → right → node). In-order traversal of a BST gives you sorted output.",
      videoUrl: "https://www.youtube.com/watch?v=BHB0B1jFKQc",
      videoTitle: "Tree Traversals — take U forward",
      articleUrl: "https://www.geeksforgeeks.org/tree-traversals-inorder-preorder-and-postorder/",
      articleTitle: "Tree Traversals — GeeksforGeeks",
    },
    {
      title: "Depth & balance",
      concept: "Tree height follows a recurrence over left and right subtrees.",
      focus: "Compute height bottom-up for a small tree.",
      practice: "Maximum Depth of Binary Tree",
      practiceUrl: "https://leetcode.com/problems/maximum-depth-of-binary-tree/",
      resource: "Tree patterns",
      resourceUrl: a2z,
      edgeCase: "Count nodes or edges consistently.",
      topicIntro: "The height of a tree is the longest path from the root to any leaf. Computing it recursively: height(node) = 1 + max(height(left), height(right)). A balanced tree has roughly equal height on both sides — this keeps BST operations fast at O(log n).",
      videoUrl: "https://www.youtube.com/watch?v=hTM3phVI6YQ",
      videoTitle: "Max Depth of Binary Tree — NeetCode",
      articleUrl: "https://www.geeksforgeeks.org/write-a-c-program-to-find-the-maximum-depth-or-height-of-a-tree/",
      articleTitle: "Tree Height — GeeksforGeeks",
    },
    {
      title: "Binary search trees",
      concept: "Every left value is smaller and every right value is larger.",
      focus: "Search and insert while preserving the ordering rule.",
      practice: "Search in a Binary Search Tree",
      practiceUrl: "https://leetcode.com/problems/search-in-a-binary-search-tree/",
      resource: "BST visualizer",
      resourceUrl: visualgo,
      edgeCase: "What happens with a missing key?",
      topicIntro: "A BST organizes data so every left child is smaller and every right child is larger. Searching works like binary search — go left if target is smaller, right if larger. Average case O(log n). If you insert sorted data, it degenerates to a linked list — that's why balanced BSTs (AVL, Red-Black) exist.",
      videoUrl: "https://www.youtube.com/watch?v=pYT9F8_LFTM",
      videoTitle: "Binary Search Tree — take U forward",
      articleUrl: "https://www.geeksforgeeks.org/binary-search-tree-data-structure/",
      articleTitle: "BST Data Structure — GeeksforGeeks",
    },
    {
      title: "Heap basics",
      concept: "A heap keeps the best item at the root using a complete tree.",
      focus: "Trace insert and bubble-up in a min-heap.",
      practice: "Kth Largest Element",
      practiceUrl: "https://leetcode.com/problems/kth-largest-element-in-an-array/",
      resource: "Heap visualizer",
      resourceUrl: visualgo,
      edgeCase: "Know whether your heap is min-first or max-first.",
      topicIntro: "A heap is a complete binary tree where every parent is smaller (min-heap) or larger (max-heap) than its children. The minimum/maximum is always at the root — O(1) access. Insertion 'bubbles up' to restore order. Used to implement priority queues — essential for Dijkstra's algorithm.",
      videoUrl: "https://www.youtube.com/watch?v=0wPlzMU-k00",
      videoTitle: "Heap Data Structure — Abdul Bari",
      articleUrl: "https://www.geeksforgeeks.org/heap-data-structure/",
      articleTitle: "Heap Data Structure — GeeksforGeeks",
    },
    {
      title: "Heap pop",
      concept: "Remove the root, move the last value, then restore order downward.",
      focus: "Trace heapify-down step by step.",
      practice: "Last Stone Weight",
      practiceUrl: "https://leetcode.com/problems/last-stone-weight/",
      resource: "Priority queues",
      resourceUrl: a2z,
      edgeCase: "Stop when both children are already valid.",
      topicIntro: "Removing the minimum from a heap: replace the root with the last element, then 'sift down' — repeatedly swap with the smaller child until both children are larger. O(log n). Priority queues are heaps in disguise, used in Dijkstra's, task scheduling, and merge-k-sorted-lists.",
      videoUrl: "https://www.youtube.com/watch?v=AE5I0xACpZs",
      videoTitle: "Heap Operations — William Fiset",
      articleUrl: "https://www.geeksforgeeks.org/heap-sort/",
      articleTitle: "Heap Sort & Sift Down — GeeksforGeeks",
    },
    {
      title: "Trees review",
      concept: "Recursive structure needs a clear contract at every node.",
      focus: "Re-solve max depth and write its recurrence.",
      practice: "Towers",
      practiceUrl: "https://cses.fi/problemset/task/1073",
      resource: "Tree & heap review",
      resourceUrl: cses,
      edgeCase: "Which subtree result do you need to return?",
      topicIntro: "Trees are arguably the most important data structure in CS — file systems, HTML DOM, databases (B-trees), compilers (AST), and more are all trees. The key insight: every tree problem has a self-similar recursive structure. Solve for left, solve for right, combine.",
      videoUrl: "https://www.youtube.com/watch?v=fAAZixBzIAI",
      videoTitle: "Trees & Heaps Review — take U forward",
      articleUrl: "https://www.geeksforgeeks.org/binary-tree-data-structure/",
      articleTitle: "Binary Tree — GeeksforGeeks",
    },
  ] },
  { title: "Graph Foundations", days: [
    {
      title: "Graph representation",
      concept: "An adjacency list stores only real edges; a matrix stores every possibility.",
      focus: "Build both representations for a five-node graph.",
      practice: "Building Roads",
      practiceUrl: "https://cses.fi/problemset/task/1666",
      resource: "Graph visualizer",
      resourceUrl: visualgo,
      edgeCase: "Does an undirected edge need two entries?",
      topicIntro: "A graph is a set of nodes (vertices) connected by edges — think a map of cities and roads. Adjacency list: each node stores a list of its neighbors (memory-efficient for sparse graphs). Adjacency matrix: a grid where [i][j]=1 means an edge exists (fast edge lookup, O(V²) memory).",
      videoUrl: "https://www.youtube.com/watch?v=M3_pLsDdeuU",
      videoTitle: "Graph Representation — take U forward",
      articleUrl: "https://www.geeksforgeeks.org/graph-and-its-representations/",
      articleTitle: "Graph Representations — GeeksforGeeks",
    },
    {
      title: "Depth-first search",
      concept: "DFS explores one branch deeply before it backtracks.",
      focus: "Trace recursive DFS with a visited set.",
      practice: "Number of Islands",
      practiceUrl: "https://leetcode.com/problems/number-of-islands/",
      resource: "DFS patterns",
      resourceUrl: a2z,
      edgeCase: "Mark visited before recursing.",
      topicIntro: "DFS dives as deep as possible down one path before backtracking. Think of exploring a maze: go as far as you can in one direction, turn back at a dead end. Uses a stack (or recursion). Used for: cycle detection, topological sort, connected components, tree traversal.",
      videoUrl: "https://www.youtube.com/watch?v=Y40bRyPQQr0",
      videoTitle: "DFS Algorithm — take U forward",
      articleUrl: "https://www.geeksforgeeks.org/depth-first-search-or-dfs-for-a-graph/",
      articleTitle: "DFS — GeeksforGeeks",
    },
    {
      title: "Breadth-first search",
      concept: "BFS visits distance d before distance d+1.",
      focus: "Write queue operations and distance updates.",
      practice: "Shortest Path in Binary Matrix",
      practiceUrl: "https://leetcode.com/problems/shortest-path-in-binary-matrix/",
      resource: "BFS visualizer",
      resourceUrl: visualgo,
      edgeCase: "Enqueue a node only once.",
      topicIntro: "BFS explores all nodes at distance 1 before distance 2, then distance 3, and so on. Think of dropping a stone in water — ripples expand outward layer by layer. This guarantees shortest path in unweighted graphs. Uses a queue (FIFO) to process nodes in discovery order.",
      videoUrl: "https://www.youtube.com/watch?v=-tgVpUgsQ5k",
      videoTitle: "BFS Algorithm — take U forward",
      articleUrl: "https://www.geeksforgeeks.org/breadth-first-search-or-bfs-for-a-graph/",
      articleTitle: "BFS — GeeksforGeeks",
    },
    {
      title: "Components",
      concept: "A connected component is everything reachable from one unseen start.",
      focus: "Count components by starting DFS/BFS only on unvisited nodes.",
      practice: "Counting Rooms",
      practiceUrl: "https://cses.fi/problemset/task/1192",
      resource: "Graph traversal",
      resourceUrl: a2z,
      edgeCase: "A new search means a new component.",
      topicIntro: "A connected component is a group of nodes where every node can reach every other. To count components: scan all nodes, and for each unvisited node, start a DFS/BFS to mark its entire component. Each time you start a new search from an unvisited node, you've found a new component.",
      videoUrl: "https://www.youtube.com/watch?v=sY4p_hTExos",
      videoTitle: "Connected Components — take U forward",
      articleUrl: "https://www.geeksforgeeks.org/connected-components-in-an-undirected-graph/",
      articleTitle: "Connected Components — GeeksforGeeks",
    },
    {
      title: "Graph cycles",
      concept: "A cycle check remembers the route that led to a node.",
      focus: "Track parent nodes in an undirected DFS.",
      practice: "Cycle Detection",
      practiceUrl: a2z,
      resource: "Cycle patterns",
      resourceUrl: a2z,
      edgeCase: "The parent edge is not a back edge.",
      topicIntro: "A cycle in a graph means you can start at a node, follow edges, and return to where you started. In undirected graphs, DFS detects cycles by checking if a neighbor is visited AND is not the parent we came from. In directed graphs, track nodes currently on the recursion stack.",
      videoUrl: "https://www.youtube.com/watch?v=BPlrALf1LDU",
      videoTitle: "Cycle Detection — take U forward",
      articleUrl: "https://www.geeksforgeeks.org/detect-cycle-in-a-graph/",
      articleTitle: "Cycle Detection in Graph — GeeksforGeeks",
    },
    {
      title: "Graph review",
      concept: "Representation, visited state, and traversal order decide the algorithm.",
      focus: "Re-solve one grid traversal from memory.",
      practice: "Message Route",
      practiceUrl: "https://cses.fi/problemset/task/1667",
      resource: "Graph foundations",
      resourceUrl: cses,
      edgeCase: "When should you store a parent pointer?",
      topicIntro: "Graphs model everything: social networks, maps, dependencies, the internet. BFS for shortest path, DFS for exhaustive exploration. Today you consolidate the core traversal patterns that unlock all advanced graph algorithms.",
      videoUrl: "https://www.youtube.com/watch?v=M3_pLsDdeuU",
      videoTitle: "Graph Foundations Review — take U forward",
      articleUrl: "https://www.geeksforgeeks.org/graph-data-structure-and-algorithms/",
      articleTitle: "Graph Algorithms — GeeksforGeeks",
    },
  ] },
  { title: "Graph Algorithms", days: [
    {
      title: "Topological sort",
      concept: "A DAG has an order where every directed edge points forward.",
      focus: "Run Kahn's algorithm using indegrees and a queue.",
      practice: "Course Schedule",
      practiceUrl: "https://leetcode.com/problems/course-schedule/",
      resource: "Topological sorting",
      resourceUrl: a2z,
      edgeCase: "If nodes remain, the graph contains a cycle.",
      topicIntro: "Topological sort orders nodes in a directed acyclic graph (DAG) so every edge points 'forward'. Think of course prerequisites: you can't take Algorithms before Data Structures. Kahn's algorithm processes nodes with no remaining prerequisites first, removing them and unlocking the next batch.",
      videoUrl: "https://www.youtube.com/watch?v=cIBFEhD77b4",
      videoTitle: "Topological Sort — take U forward",
      articleUrl: "https://www.geeksforgeeks.org/topological-sorting/",
      articleTitle: "Topological Sort — GeeksforGeeks",
    },
    {
      title: "Dijkstra",
      concept: "Relaxation improves the best-known distance to a vertex.",
      focus: "Trace a min-heap of candidate distances.",
      practice: "Network Delay Time",
      practiceUrl: "https://leetcode.com/problems/network-delay-time/",
      resource: "Shortest paths",
      resourceUrl: mit,
      edgeCase: "Skip stale heap entries.",
      topicIntro: "Dijkstra finds the shortest path from a source to all nodes in a weighted graph (no negative edges). It greedily picks the unvisited node with smallest known distance, then updates (relaxes) its neighbors. A min-heap makes each pick O(log V). Think of it as 'expanding circles' of shortest distances.",
      videoUrl: "https://www.youtube.com/watch?v=V6H1qAeB-l4",
      videoTitle: "Dijkstra's Algorithm — take U forward",
      articleUrl: "https://www.geeksforgeeks.org/dijkstras-shortest-path-algorithm-greedy-algo-7/",
      articleTitle: "Dijkstra's Algorithm — GeeksforGeeks",
    },
    {
      title: "Disjoint sets",
      concept: "Union-find represents changing connected components efficiently.",
      focus: "Implement find with path compression and union by size.",
      practice: "Number of Provinces",
      practiceUrl: "https://leetcode.com/problems/number-of-provinces/",
      resource: "DSU patterns",
      resourceUrl: a2z,
      edgeCase: "Always union roots, never arbitrary nodes.",
      topicIntro: "Disjoint Set Union (DSU / Union-Find) tracks which nodes are in the same group as edges are added. Find() tells you a node's group; Union() merges two groups. With path compression + union by rank, both are nearly O(1) — incredibly fast for dynamic connectivity problems.",
      videoUrl: "https://www.youtube.com/watch?v=aBxjDBC4M1U",
      videoTitle: "Disjoint Set Union — take U forward",
      articleUrl: "https://www.geeksforgeeks.org/union-find/",
      articleTitle: "Union-Find (DSU) — GeeksforGeeks",
    },
    {
      title: "Minimum spanning tree",
      concept: "Kruskal adds the cheapest edge that does not create a cycle.",
      focus: "Sort edges and test each with DSU.",
      practice: "Road Reparation",
      practiceUrl: "https://cses.fi/problemset/task/1675",
      resource: "MST visualizer",
      resourceUrl: visualgo,
      edgeCase: "A disconnected graph has no spanning tree.",
      topicIntro: "A Minimum Spanning Tree (MST) connects all nodes using the minimum total edge weight. Kruskal's: sort all edges by weight, greedily add the smallest that doesn't create a cycle (use DSU to check). Used in network design — how to cable all offices for minimum wire length.",
      videoUrl: "https://www.youtube.com/watch?v=DMnDM_sxVig",
      videoTitle: "Kruskal's MST — take U forward",
      articleUrl: "https://www.geeksforgeeks.org/kruskals-minimum-spanning-tree-algorithm-greedy-algo-2/",
      articleTitle: "Kruskal's Algorithm — GeeksforGeeks",
    },
    {
      title: "Bellman-Ford idea",
      concept: "Repeated relaxation handles negative edges when Dijkstra cannot.",
      focus: "Perform one full relaxation pass by hand.",
      practice: "Bellman-Ford",
      practiceUrl: a2z,
      resource: "Weighted paths",
      resourceUrl: mit,
      edgeCase: "A final improving pass signals a negative cycle.",
      topicIntro: "Bellman-Ford handles graphs with negative edge weights — Dijkstra breaks there. It relaxes ALL edges V-1 times. Each pass guarantees shortest paths of at most k edges are correct. If a V-th pass still improves a distance, there's a negative cycle (an infinite loop of savings).",
      videoUrl: "https://www.youtube.com/watch?v=0vVofAhAYjc",
      videoTitle: "Bellman-Ford — take U forward",
      articleUrl: "https://www.geeksforgeeks.org/bellman-ford-algorithm-dp-23/",
      articleTitle: "Bellman-Ford Algorithm — GeeksforGeeks",
    },
    {
      title: "Graph algorithms review",
      concept: "The edge weights and graph shape tell you which algorithm fits.",
      focus: "Choose BFS, Dijkstra, DSU, or topological sort from four prompts.",
      practice: "Shortest Routes I",
      practiceUrl: "https://cses.fi/problemset/task/1671",
      resource: "Graph algorithms",
      resourceUrl: cses,
      edgeCase: "Can your chosen algorithm handle every edge weight?",
      topicIntro: "Picking the right algorithm is a skill. Unweighted shortest path → BFS. Weighted, no negatives → Dijkstra. With negatives → Bellman-Ford. MST → Kruskal. Ordering dependencies → Topological sort. Dynamic connectivity → DSU. Today you practice making this choice quickly.",
      videoUrl: "https://www.youtube.com/watch?v=M3_pLsDdeuU",
      videoTitle: "Graph Algorithm Selection — take U forward",
      articleUrl: "https://www.geeksforgeeks.org/graph-data-structure-and-algorithms/",
      articleTitle: "Graph Algorithms Cheatsheet — GeeksforGeeks",
    },
  ] },
  { title: "Greedy & Intervals", days: [
    {
      title: "Greedy proof",
      concept: "A greedy choice needs an exchange argument or a counterexample test.",
      focus: "Try to break a tempting local choice before trusting it.",
      practice: "Assign Cookies",
      practiceUrl: "https://leetcode.com/problems/assign-cookies/",
      resource: "Greedy patterns",
      resourceUrl: a2z,
      edgeCase: "What optimal solution can you exchange with yours?",
      topicIntro: "Greedy algorithms make the locally best choice at every step, hoping it leads to a globally optimal solution. They're fast but not always correct. You must prove your choice works with an exchange argument: 'if the optimal solution differs, I can swap it to look like mine without getting worse.'",
      videoUrl: "https://www.youtube.com/watch?v=HzeK7g8cD0Y",
      videoTitle: "Greedy Algorithms Intro — Abdul Bari",
      articleUrl: "https://www.geeksforgeeks.org/greedy-algorithms/",
      articleTitle: "Greedy Algorithms — GeeksforGeeks",
    },
    {
      title: "Activity selection",
      concept: "Choosing the earliest finishing compatible interval leaves the most room.",
      focus: "Sort intervals by end time and trace selection.",
      practice: "Movie Festival",
      practiceUrl: "https://cses.fi/problemset/task/1629",
      resource: "Interval patterns",
      resourceUrl: a2z,
      edgeCase: "How do you handle touching endpoints?",
      topicIntro: "Activity Selection: given events with start/end times, pick the maximum number of non-overlapping events. The greedy insight: always pick the event that ends earliest — it finishes first and leaves maximum room for future events. Sort by end time and greedily pick compatible ones.",
      videoUrl: "https://www.youtube.com/watch?v=iEchbCHFvNM",
      videoTitle: "Activity Selection — Abdul Bari",
      articleUrl: "https://www.geeksforgeeks.org/activity-selection-problem-greedy-algo-1/",
      articleTitle: "Activity Selection Problem — GeeksforGeeks",
    },
    {
      title: "Merge intervals",
      concept: "Sorted interval starts make overlap detection local.",
      focus: "Keep one running merged interval.",
      practice: "Merge Intervals",
      practiceUrl: "https://leetcode.com/problems/merge-intervals/",
      resource: "Intervals",
      resourceUrl: a2z,
      edgeCase: "Do [1,4] and [4,5] overlap in this problem?",
      topicIntro: "Merging overlapping intervals: sort by start time. Then scan: if the current interval overlaps the last merged one (current.start ≤ last.end), extend the merged end. Otherwise start a new group. Sorting is the key — it turns complex pairwise comparison into a simple linear scan.",
      videoUrl: "https://www.youtube.com/watch?v=44H3cEC2fFM",
      videoTitle: "Merge Intervals — NeetCode",
      articleUrl: "https://www.geeksforgeeks.org/merging-intervals/",
      articleTitle: "Merge Intervals — GeeksforGeeks",
    },
    {
      title: "Meeting rooms",
      concept: "Two sorted endpoint streams reveal the maximum concurrent intervals.",
      focus: "Trace arrival and departure pointers.",
      practice: "Meeting Rooms II",
      practiceUrl: "https://leetcode.com/problems/meeting-rooms-ii/",
      resource: "Sweep lines",
      resourceUrl: a2z,
      edgeCase: "Process end before start when times tie if rooms can be reused.",
      topicIntro: "How many conference rooms do you need? Sort start times and end times separately. Use two pointers: if the next meeting starts before the earliest-ending meeting ends, you need a new room. Otherwise, reuse the freed room. This is the sweep line technique.",
      videoUrl: "https://www.youtube.com/watch?v=FdzJmTx9fHg",
      videoTitle: "Meeting Rooms II — NeetCode",
      articleUrl: "https://www.geeksforgeeks.org/minimum-number-of-platforms-required-for-a-railway-train-station-set-2-map-based-approach/",
      articleTitle: "Meeting Rooms / Min Platforms — GeeksforGeeks",
    },
    {
      title: "Jump game",
      concept: "A running farthest reach can summarize many possible jumps.",
      focus: "Update reach while scanning left to right.",
      practice: "Jump Game",
      practiceUrl: "https://leetcode.com/problems/jump-game/",
      resource: "Greedy reachability",
      resourceUrl: a2z,
      edgeCase: "Stop if the current index is already unreachable.",
      topicIntro: "Jump Game: can you reach the last index if each element tells you the max jump? Greedy: track the farthest index reachable so far. Scan left to right — if you're at an index beyond your farthest reach, you're stuck. Otherwise update the max reach. One pass, O(n).",
      videoUrl: "https://www.youtube.com/watch?v=Yan0cv2cLy8",
      videoTitle: "Jump Game — NeetCode",
      articleUrl: "https://www.geeksforgeeks.org/jump-game/",
      articleTitle: "Jump Game — GeeksforGeeks",
    },
    {
      title: "Greedy review",
      concept: "A correct local choice needs a reason, not a familiar shape.",
      focus: "Write a two-sentence proof sketch for one solved greedy problem.",
      practice: "Greedy revision",
      practiceUrl: a2z,
      resource: "Greedy algorithms",
      resourceUrl: mit,
      edgeCase: "Can you construct a counterexample to a different rule?",
      topicIntro: "Greedy algorithms are elegant but dangerous — they look correct until they aren't. The discipline is always proving your choice: 'I can exchange the optimal with my choice without loss.' Write that proof in two sentences for one problem. This habit separates solid from shaky reasoning.",
      videoUrl: "https://www.youtube.com/watch?v=HzeK7g8cD0Y",
      videoTitle: "Greedy Strategy Review — Abdul Bari",
      articleUrl: "https://www.geeksforgeeks.org/greedy-algorithms/",
      articleTitle: "Greedy Algorithms — GeeksforGeeks",
    },
  ] },
  { title: "DP Foundations", days: [
    {
      title: "Fibonacci three ways",
      concept: "Memoization and tabulation reuse overlapping subproblems.",
      focus: "Implement recursion, memoization, and tabulation; compare calls.",
      practice: "Climbing Stairs",
      practiceUrl: "https://leetcode.com/problems/climbing-stairs/",
      resource: "DP foundations",
      resourceUrl: a2z,
      edgeCase: "State the base values explicitly.",
      topicIntro: "Dynamic programming avoids solving the same subproblem twice. Fibonacci is the perfect intro: fib(5) calls fib(4) and fib(3), but fib(4) also calls fib(3) — computed twice! Memoization caches results top-down; tabulation builds results bottom-up. Both turn exponential to linear.",
      videoUrl: "https://www.youtube.com/watch?v=tyB0ztf0DNY",
      videoTitle: "DP Introduction (Fibonacci) — take U forward",
      articleUrl: "https://www.geeksforgeeks.org/dynamic-programming/",
      articleTitle: "Dynamic Programming — GeeksforGeeks",
    },
    {
      title: "State & transition",
      concept: "A DP state records exactly what the next decision needs.",
      focus: "Write state, choices, transition, and base case before code.",
      practice: "Frog Jump",
      practiceUrl: a2z,
      resource: "DP state design",
      resourceUrl: mit,
      edgeCase: "Does your state omit a value the future needs?",
      topicIntro: "Designing DP is about identifying the state. The state captures everything you need for the next decision — no more, no less. For each state, list your choices (transitions). Write the recurrence: dp[state] = best over all choices. Define base cases. Only then write code.",
      videoUrl: "https://www.youtube.com/watch?v=tyB0ztf0DNY",
      videoTitle: "DP State Design — take U forward",
      articleUrl: "https://www.geeksforgeeks.org/tabulation-vs-memoization/",
      articleTitle: "DP State & Transitions — GeeksforGeeks",
    },
    {
      title: "Non-adjacent maximum",
      concept: "At each index, choose take or skip using prior optimal states.",
      focus: "Trace include/exclude decisions on six values.",
      practice: "House Robber",
      practiceUrl: "https://leetcode.com/problems/house-robber/",
      resource: "1D DP patterns",
      resourceUrl: a2z,
      edgeCase: "What does zero items return?",
      topicIntro: "House Robber: rob non-adjacent houses for maximum total. At each house you choose: rob it (add its value + skip the previous) or skip it (take whatever was best up to the previous house). dp[i] = max(dp[i-2] + nums[i], dp[i-1]). This 'include or skip' pattern appears in many DP problems.",
      videoUrl: "https://www.youtube.com/watch?v=73r3KWiEvyk",
      videoTitle: "House Robber — NeetCode",
      articleUrl: "https://www.geeksforgeeks.org/find-maximum-possible-stolen-value-houses/",
      articleTitle: "House Robber Pattern — GeeksforGeeks",
    },
    {
      title: "Grid paths",
      concept: "A two-dimensional state follows dependencies from top and left.",
      focus: "Fill a small DP table by hand.",
      practice: "Unique Paths",
      practiceUrl: "https://leetcode.com/problems/unique-paths/",
      resource: "2D DP",
      resourceUrl: a2z,
      edgeCase: "Block or initialize the first row and column carefully.",
      topicIntro: "In grid DP, the state is a cell (row, col) and you fill the table one row at a time. Unique Paths: dp[i][j] = dp[i-1][j] + dp[i][j-1] because you can only come from above or from the left. First row and column are all 1s. Always fill a small 3×3 grid by hand first.",
      videoUrl: "https://www.youtube.com/watch?v=IlEsdxuD4lY",
      videoTitle: "Unique Paths — NeetCode",
      articleUrl: "https://www.geeksforgeeks.org/count-all-possible-paths-from-top-left-to-bottom-right/",
      articleTitle: "Grid Paths DP — GeeksforGeeks",
    },
    {
      title: "Coin change",
      concept: "The same recurrence shape can minimize cost or count combinations.",
      focus: "Decide whether order matters before filling the table.",
      practice: "Coin Change",
      practiceUrl: "https://leetcode.com/problems/coin-change/",
      resource: "DP patterns",
      resourceUrl: a2z,
      edgeCase: "Use an impossible sentinel that cannot be mistaken for an answer.",
      topicIntro: "Coin Change: minimum number of coins to make amount X? dp[amount] = min over all coins of (1 + dp[amount - coin]). Initialize dp[0]=0 and everything else as infinity. The same structure can count the NUMBER of ways — just swap min for addition.",
      videoUrl: "https://www.youtube.com/watch?v=H9bfqozjoqs",
      videoTitle: "Coin Change — NeetCode",
      articleUrl: "https://www.geeksforgeeks.org/coin-change-dp-7/",
      articleTitle: "Coin Change DP — GeeksforGeeks",
    },
    {
      title: "DP review",
      concept: "State first, then transition; loops come last.",
      focus: "Explain one DP table to an imaginary beginner.",
      practice: "Dice Combinations",
      practiceUrl: "https://cses.fi/problemset/task/1633",
      resource: "DP practice",
      resourceUrl: cses,
      edgeCase: "Which smaller states must already be known?",
      topicIntro: "DP mastery comes from explaining your solutions, not just writing them. Can you explain why dp[i] depends on dp[i-1] and dp[i-2]? Can you show the table filling order? Today you practice teaching DP to an imaginary beginner — the best test of true understanding.",
      videoUrl: "https://www.youtube.com/watch?v=tyB0ztf0DNY",
      videoTitle: "DP Patterns Review — take U forward",
      articleUrl: "https://www.geeksforgeeks.org/dynamic-programming/",
      articleTitle: "DP Problems Collection — GeeksforGeeks",
    },
  ] },
  { title: "DP & Strings", days: [
    {
      title: "0/1 knapsack",
      concept: "Capacity and item position define the subproblem.",
      focus: "Build a small table and compare take versus skip.",
      practice: "0/1 Knapsack",
      practiceUrl: a2z,
      resource: "Knapsack",
      resourceUrl: mit,
      edgeCase: "Never reuse an item in 0/1 knapsack.",
      topicIntro: "The 0/1 Knapsack problem: given items with weights and values, maximize value in a bag of capacity W. Each item can be taken (1) or not (0). dp[i][w] = max value using first i items with capacity w. Either skip item i (dp[i-1][w]) or take it (dp[i-1][w-weight[i]] + value[i]).",
      videoUrl: "https://www.youtube.com/watch?v=mGfK-j9gAQA",
      videoTitle: "0/1 Knapsack — take U forward",
      articleUrl: "https://www.geeksforgeeks.org/0-1-knapsack-problem-dp-10/",
      articleTitle: "0/1 Knapsack — GeeksforGeeks",
    },
    {
      title: "Longest common subsequence",
      concept: "Two changing indices usually require a two-dimensional state.",
      focus: "Trace match and mismatch transitions for two short strings.",
      practice: "Longest Common Subsequence",
      practiceUrl: "https://leetcode.com/problems/longest-common-subsequence/",
      resource: "String DP",
      resourceUrl: a2z,
      edgeCase: "What happens when either index reaches the end?",
      topicIntro: "LCS finds the longest sequence of characters common to two strings (not necessarily consecutive). State: dp[i][j] = LCS of first i chars of s1 and first j chars of s2. If s1[i]==s2[j], extend the diagonal (dp[i-1][j-1]+1). Otherwise, take the best of skipping one char from either string.",
      videoUrl: "https://www.youtube.com/watch?v=sSno9rV8Rhg",
      videoTitle: "LCS — take U forward",
      articleUrl: "https://www.geeksforgeeks.org/longest-common-subsequence-dp-4/",
      articleTitle: "Longest Common Subsequence — GeeksforGeeks",
    },
    {
      title: "Edit distance",
      concept: "Insert, delete, and replace are competing transitions on prefix pairs.",
      focus: "Fill a 3×3 edit-distance grid by hand.",
      practice: "Edit Distance",
      practiceUrl: "https://leetcode.com/problems/edit-distance/",
      resource: "DP on strings",
      resourceUrl: mit,
      edgeCase: "Initialize the empty-string row and column.",
      topicIntro: "Edit Distance: minimum operations (insert, delete, replace) to convert one string to another. Used in spell-checkers and DNA comparison. dp[i][j] = cost to convert first i chars of s1 to first j chars of s2. If chars match, no cost; otherwise pick cheapest of insert, delete, or replace.",
      videoUrl: "https://www.youtube.com/watch?v=XYi2-LPrwm4",
      videoTitle: "Edit Distance — NeetCode",
      articleUrl: "https://www.geeksforgeeks.org/edit-distance-dp-5/",
      articleTitle: "Edit Distance — GeeksforGeeks",
    },
    {
      title: "Sliding window",
      concept: "A window stays valid through a maintained invariant.",
      focus: "Trace left and right pointers on a fixed-size sum.",
      practice: "Maximum Average Subarray I",
      practiceUrl: "https://leetcode.com/problems/maximum-average-subarray-i/",
      resource: "Sliding window",
      resourceUrl: a2z,
      edgeCase: "Remove the outgoing value before advancing.",
      topicIntro: "Sliding window maintains a contiguous subarray (window) that satisfies some condition. Instead of recomputing from scratch, you slide: add the new right element and remove the old left element. Fixed-size windows always remove when the window exceeds size k. Turns O(n²) into O(n).",
      videoUrl: "https://www.youtube.com/watch?v=jM2dhDPtoXY",
      videoTitle: "Sliding Window — take U forward",
      articleUrl: "https://www.geeksforgeeks.org/window-sliding-technique/",
      articleTitle: "Sliding Window Technique — GeeksforGeeks",
    },
    {
      title: "No-repeat substring",
      concept: "A map can tell you how far a window's left side must move.",
      focus: "Trace duplicate handling and keep the maximum length.",
      practice: "Longest Substring Without Repeating Characters",
      practiceUrl: "https://leetcode.com/problems/longest-substring-without-repeating-characters/",
      resource: "Variable windows",
      resourceUrl: a2z,
      edgeCase: "Never move left backward.",
      topicIntro: "Variable sliding window: the window size changes based on validity. For 'no repeating characters', expand right and shrink from left whenever a duplicate appears. A hash map stores the last seen index of each character, letting you jump the left pointer directly past the previous occurrence.",
      videoUrl: "https://www.youtube.com/watch?v=wiGpQwVHdE0",
      videoTitle: "Longest Substring No Repeat — NeetCode",
      articleUrl: "https://www.geeksforgeeks.org/length-of-the-longest-substring-without-repeating-characters/",
      articleTitle: "Longest Substring No Repeat — GeeksforGeeks",
    },
    {
      title: "DP & strings review",
      concept: "Index meaning is the contract behind every string algorithm.",
      focus: "Re-solve one DP or window question and name its invariant.",
      practice: "DP revision",
      practiceUrl: leet,
      resource: "Algorithm practice",
      resourceUrl: leet,
      edgeCase: "Is your answer a substring, subsequence, count, or cost?",
      topicIntro: "String DP and sliding window share a theme: track where you are in the string with an index (or two), and use stored results to avoid recomputation. The most common mistake: confusing substrings (contiguous) with subsequences (can skip). Always clarify which one the problem asks for.",
      videoUrl: "https://www.youtube.com/watch?v=jM2dhDPtoXY",
      videoTitle: "String DP & Sliding Window — take U forward",
      articleUrl: "https://www.geeksforgeeks.org/dynamic-programming-on-strings/",
      articleTitle: "DP on Strings — GeeksforGeeks",
    },
  ] },
  { title: "Consolidate", days: [
    {
      title: "Arrays mixed set",
      concept: "Recognize scans, maps, prefixes, and two-pointer cues.",
      focus: "Solve one array problem with a timed 30-minute limit.",
      practice: "Array mixed set",
      practiceUrl: a2z,
      resource: "A2Z revision",
      resourceUrl: a2z,
      edgeCase: "Write the brute-force idea before optimizing.",
      topicIntro: "This is consolidation week — no new topics. You've covered arrays, hashing, sorting, search, linked lists, stacks, trees, graphs, greedy, and DP. Now mix them under time pressure. The skill you're training is pattern recognition: seeing a cue in a problem and knowing which tool to reach for.",
      videoUrl: "https://www.youtube.com/watch?v=RBSGKlAvoiM",
      videoTitle: "Array Patterns Review — take U forward",
      articleUrl: a2z,
      articleTitle: "A2Z DSA Sheet — take U forward",
    },
    {
      title: "Trees & graphs mixed set",
      concept: "Model the structure before picking traversal or priority queue.",
      focus: "Solve one tree and one graph prompt without notes.",
      practice: "Graph mixed set",
      practiceUrl: cses,
      resource: "CSES revision",
      resourceUrl: cses,
      edgeCase: "What representation makes the problem easiest?",
      topicIntro: "Tree and graph problems share traversal DNA — but the structure matters. Trees are hierarchical with no cycles; graphs can have both. When you see a problem: first identify the structure, then pick the traversal (DFS? BFS?), then identify what you're tracking (distances? components? cycles?).",
      videoUrl: "https://www.youtube.com/watch?v=M3_pLsDdeuU",
      videoTitle: "Trees & Graphs Mixed — take U forward",
      articleUrl: cses,
      articleTitle: "CSES Problem Set — Trees & Graphs",
    },
    {
      title: "DP & greedy mixed set",
      concept: "Distinguish a provable local choice from overlapping subproblems.",
      focus: "Classify five prompts as greedy, DP, or neither.",
      practice: "DP mixed set",
      practiceUrl: a2z,
      resource: "Pattern revision",
      resourceUrl: a2z,
      edgeCase: "Can you prove the greedy choice?",
      topicIntro: "Greedy vs DP is the hardest meta-skill. Greedy: one locally optimal choice per step, no reconsideration. DP: explore all possible choices and cache results. Test: can you prove a greedy exchange argument? If yes, use greedy. If you need to track multiple possible states, use DP.",
      videoUrl: "https://www.youtube.com/watch?v=tyB0ztf0DNY",
      videoTitle: "Greedy vs DP — take U forward",
      articleUrl: gfg,
      articleTitle: "Greedy vs DP — GeeksforGeeks",
    },
    {
      title: "Re-solve your misses",
      concept: "A solved mistake is more valuable than a fresh familiar problem.",
      focus: "Pick three mistake-log entries and solve them cleanly.",
      practice: "Your error log",
      practiceUrl: leet,
      resource: "Retrieval practice",
      resourceUrl: mit,
      edgeCase: "What clue should trigger this pattern next time?",
      topicIntro: "Re-solving mistakes is the most effective study method — retrieval practice. Every missed problem signals either a wrong concept model or a pattern you couldn't recognize under pressure. Fix both by solving it clean from scratch today.",
      videoUrl: "https://www.youtube.com/watch?v=RBSGKlAvoiM",
      videoTitle: "Learning From Mistakes — William Fiset",
      articleUrl: "https://www.geeksforgeeks.org/practice-for-cracking-any-coding-interview/",
      articleTitle: "How to Practice DSA Effectively — GeeksforGeeks",
    },
    {
      title: "Pattern sheet",
      concept: "A pattern sheet records cues, invariants, and common traps.",
      focus: "Create a one-page personal sheet for five topics.",
      practice: "Build your pattern sheet",
      practiceUrl: a2z,
      resource: "DSA roadmap",
      resourceUrl: a2z,
      edgeCase: "Can you state each invariant in one sentence?",
      topicIntro: "A personal pattern sheet is your most valuable interview tool. For each topic write: (1) recognition cue — what in the problem tells you to use this pattern, (2) the invariant — what stays true throughout, (3) the common trap — what almost gets you. One sentence each.",
      videoUrl: "https://www.youtube.com/watch?v=RBSGKlAvoiM",
      videoTitle: "DSA Patterns Cheatsheet — take U forward",
      articleUrl: a2z,
      articleTitle: "A2Z DSA Sheet — Full Pattern List",
    },
    {
      title: "Final mock",
      concept: "A retrospective turns a timed set into a new learning plan.",
      focus: "Take a 75-minute mixed mock and record your next three gaps.",
      practice: "CSES problem set",
      practiceUrl: cses,
      resource: "Full review",
      resourceUrl: cses,
      edgeCase: "Which mistakes came from knowledge versus time pressure?",
      topicIntro: "Your final mock is not about your score — it's about what your performance reveals. After the mock, do a retrospective: which problems did you solve correctly? Which timed out? Separate 'I don't know the concept' from 'I know but panicked.' That gap is your next 6-week plan.",
      videoUrl: "https://www.youtube.com/watch?v=RBSGKlAvoiM",
      videoTitle: "Mock Interview Strategy — NeetCode",
      articleUrl: cses,
      articleTitle: "CSES Problem Set — Mock Practice",
    },
  ] },
];

export const lessons: Lesson[] = weeks.flatMap((week, weekIndex) =>
  week.days.map((day, dayIndex) => ({
    ...day,
    id: `w${weekIndex + 1}-d${dayIndex + 1}`,
    number: weekIndex * 6 + dayIndex + 1,
    week: weekIndex + 1,
    weekTitle: week.title,
  })),
);

export const primer = [
  ["Set up your language", "Install a compiler/interpreter, run one program, and learn how to read an error message."],
  ["Control flow", "Review variables, conditions, loops, functions, and input/output."],
  ["Think like a tester", "Write examples, boundaries, and a small brute-force solution before optimizing."],
] as const;

export function objectiveText(lesson: Lesson, language: Language) {
  const languageName = { cpp: "C++", java: "Java", python: "Python" }[language];
  return [
    `Warm up: ${lesson.concept}`,
    `Learn: read the first guide in the study path. ${lesson.focus}`,
    `Build: trace or implement “${lesson.title}” in ${languageName}.`,
    `Practice: solve ${lesson.practice}.`,
    `Reflect: ${lesson.edgeCase}`,
  ];
}

export const languageSnippets: Record<Language, string> = {
  cpp: "// C++: write a small function, test it with 3 inputs, then explain its complexity.",
  java: "// Java: write a small method, test it with 3 inputs, then explain its complexity.",
  python: "# Python: write a small function, test it with 3 inputs, then explain its complexity.",
};
