import { AnimatePresence, motion, useReducedMotion } from "framer-motion";
import { ArrowRight, BookOpen, Check, ChevronRight, Code2, ExternalLink, Flame, Github, GraduationCap, LayoutDashboard, LogOut, Menu, Plus, Rocket, Settings, Sparkles, Swords, Trophy, X } from "lucide-react";
import { FormEvent, useEffect, useState } from "react";
import { Link, Route, Router, Switch, useLocation } from "wouter";
import { Toaster } from "@/components/ui/sonner";
import { lessons, languageSnippets, objectiveText, primer, type Language, type Lesson } from "@/lib/curriculum";
import { completedLessonIds, dueResolves, getBadges, getRank, getStreak, getXp, heatmap, nextRank, type ProgressEntry, toDateKey } from "@/lib/game";
import { demoMemberProgress, demoMembers, demoProfile, demoProgress, demoProjects } from "@/lib/demo";
import { isSupabaseConfigured, type LessonNote, type Profile, type Project, supabase } from "@/lib/supabase";
import { toast } from "sonner";

type AppState = { profile: Profile; members: Profile[]; progress: ProgressEntry[]; allProgress: Record<string, ProgressEntry[]>; notes: Record<string, LessonNote>; projects: Project[] };

const initials = (name: string) => name.slice(0, 2).toUpperCase();
const routeLesson = (id: string) => "/learn/" + id;
const routeUser = (name: string) => "/u/" + name;
const navItems = [["/dashboard", "Dashboard", LayoutDashboard], ["/roadmap", "Roadmap", BookOpen], ["/leaderboard", "Leaderboard", Trophy], ["/projects", "Projects", Rocket]] as const;

function Brand() { return <Link href="/" className="brand"><span className="brand-mark">W<span>•</span></span><span>Weee<span>Cooked</span></span></Link>; }
function Avatar({ profile, className = "" }: { profile: Profile; className?: string }) { return <span className={"avatar " + className}>{profile.avatar_url ? <img src={profile.avatar_url} alt="" /> : initials(profile.public_name)}</span>; }

function Shell({ state, demo, signOut, children }: { state: AppState; demo: boolean; signOut: () => void; children: React.ReactNode }) {
  const [location] = useLocation(); const [menuOpen, setMenuOpen] = useState(false); const xp = getXp(state.progress);
  return <div className="app-shell"><header className="topbar"><Brand /><div className="topbar-center"><i />{demo ? "Demo crew mode" : "The kitchen is open"}</div><div className="topbar-actions"><Avatar profile={state.profile} className="mini-avatar" /><button onClick={() => setMenuOpen(!menuOpen)} className="menu-button" aria-label="Open navigation">{menuOpen ? <X /> : <Menu />}</button></div></header>
    <aside className={menuOpen ? "sidebar open" : "sidebar"}><div className="profile-chip"><Avatar profile={state.profile} className="big" /><div><strong>@{state.profile.public_name}</strong><small>{getRank(xp).name} · {xp} XP</small></div></div><nav>{navItems.map(([href, text, Icon]) => <Link key={href} href={href} onClick={() => setMenuOpen(false)} className={"side-link " + (location === href ? "active" : "")}><Icon size={18} />{text}</Link>)}</nav><div className="sidebar-bottom"><Link href="/settings" className={"side-link " + (location === "/settings" ? "active" : "")}><Settings size={18} />Settings</Link><button className="side-link plain" onClick={signOut}><LogOut size={18} />{demo ? "Leave demo" : "Sign out"}</button></div></aside>
    <main className="app-main">{children}</main></div>;
}

function Landing({ openDemo }: { openDemo: () => void }) {
  const [email, setEmail] = useState(""); const [sent, setSent] = useState(false); const [sending, setSending] = useState(false);
  const sendLink = async (event: FormEvent) => { event.preventDefault(); if (!supabase) { toast.message("Add Supabase details to enable sign-in. You can explore the demo right now."); return; } setSending(true); const appUrl = import.meta.env.VITE_APP_URL || window.location.origin + import.meta.env.BASE_URL; const result = await supabase.auth.signInWithOtp({ email, options: { emailRedirectTo: appUrl.replace(/\/$/, "") + "/auth/callback", shouldCreateUser: true } }); setSending(false); if (result.error) toast.error(result.error.message); else setSent(true); };
  return <div className="landing"><header className="landing-nav"><Brand /><div><a href="#how">How it works</a><a href="#road">The roadmap</a><button className="ghost-button" onClick={openDemo}>Explore demo</button></div></header><main>
    <section className="hero-grid"><div className="hero-copy"><div className="eyebrow"><Flame size={14} /> DSA, but make it a team sport</div><h1>Learn DSA from zero.<br /><em>Don’t get cooked alone.</em></h1><p>WeeeCooked turns a serious DSA path into daily quests, visible streaks, and a little friendly heat with your crew.</p>
      <form className="magic-form" onSubmit={sendLink}><label>Your email</label><div><input type="email" required value={email} onChange={(e) => setEmail(e.target.value)} placeholder="you@example.com" /><button disabled={sending}>{sending ? "Sending…" : "Send magic link"}<ArrowRight size={17} /></button></div>{sent ? <small className="success">Check your inbox. Your one-time link stays valid for 24 hours.</small> : <small>No passwords. Just a one-time sign-in link.</small>}</form>
      {!isSupabaseConfigured && <button onClick={openDemo} className="demo-link">Preview the full app with a demo crew <ArrowRight size={15} /></button>}</div>
      <div className="hero-stage"><div className="orbit one" /><div className="orbit two" /><motion.div className="hero-card rank-card" initial={{ y: 22, opacity: 0 }} animate={{ y: 0, opacity: 1 }} transition={{ duration: .5 }}><span>YOUR RANK</span><strong>Pattern Scout</strong><div className="rank-meter"><i /></div><small>760 / 800 XP</small></motion.div><motion.div className="hero-card streak-card" initial={{ y: 28, opacity: 0 }} animate={{ y: 0, opacity: 1 }} transition={{ duration: .5, delay: .12 }}><Flame fill="currentColor" /><strong>12</strong><span>day streak</span></motion.div><motion.div className="hero-card crew-card" initial={{ y: 30, opacity: 0 }} animate={{ y: 0, opacity: 1 }} transition={{ duration: .5, delay: .22 }}><div className="stacked-avatars"><b>Q</b><b>R</b><b>H</b></div><p><strong>Your crew is cooking</strong><br />3 people studied today</p></motion.div><div className="flame-shape">⌁</div></div></section>
    <section className="stats-row"><div><b>72</b><span>focused study days</span></div><div><b>5</b><span>objectives per lesson</span></div><div><b>7</b><span>badges worth earning</span></div><div><b>0</b><span>passwords to remember</span></div></section>
    <section className="story-section" id="how"><span className="section-label">THE LOOP</span><h2>Small wins. <em>Real momentum.</em></h2><div className="loop-grid"><Feature number="01" icon={<BookOpen />} title="Learn it" copy="One focused concept, a clear resource, and no random topic hopping." /><Feature number="02" icon={<Swords />} title="Do it" copy="Trace, implement, practice, and log the edge case that almost got you." /><Feature number="03" icon={<Trophy />} title="Level up" copy="Earn XP, keep your streak warm, and see your crew move together." /></div></section>
    <section className="road-section" id="road"><div><span className="section-label">THE ROADMAP</span><h2>From your first loop<br />to your first mock.</h2><p>Arrays, hashing, graphs, dynamic programming—the whole route is structured into twelve calm, practical weeks.</p><button className="dark-button" onClick={openDemo}>See the 12-week path <ArrowRight size={17} /></button></div><div className="week-list">{["Cost & Arrays", "Sorting & Search", "Trees & Heaps", "Graph Foundations", "DP Foundations", "Consolidate"].map((name, index) => <div key={name}><span>W{index === 5 ? "12" : String(index * 2 + 1).padStart(2, "0")}</span><strong>{name}</strong><i /></div>)}</div></section>
  </main><footer className="landing-footer"><Brand /><span>Built for friends who want to get dangerously good at DSA.</span></footer></div>;
}

function Feature({ number, icon, title, copy }: { number: string; icon: React.ReactNode; title: string; copy: string }) { return <article className="feature"><div className="feature-icon">{icon}</div><span>{number}</span><h3>{title}</h3><p>{copy}</p></article>; }

function Header({ eyebrow, title, copy, action, children }: { eyebrow: string; title: React.ReactNode; copy: string; action?: React.ReactNode; children: React.ReactNode }) { return <><section className="page-intro"><div><span className="eyebrow dark"><Sparkles size={14} /> {eyebrow}</span><h1>{title}</h1><p>{copy}</p></div>{action}</section>{children}</>; }

function Heatmap({ progress }: { progress: ProgressEntry[] }) { const reduce = useReducedMotion(); return <div className="heatmap">{heatmap(progress).map((day, index) => <motion.span title={day.date + ": " + day.count + " objectives"} key={day.date} initial={reduce ? false : { opacity: 0, scale: .7 }} animate={{ opacity: 1, scale: 1 }} transition={{ delay: Math.min(.3, index * .005) }} className={"heat l" + Math.min(4, day.count)} />)}</div>; }

function Dashboard({ state, changeProgress }: { state: AppState; changeProgress: (lessonId: string, index: number, completed: boolean) => Promise<void> }) {
  const done = completedLessonIds(state.progress); const current = lessons.find((lesson) => !done.has(lesson.id)) || lessons[lessons.length - 1]; const objectives = objectiveText(current, state.profile.language); const xp = getXp(state.progress); const next = nextRank(xp); const board = state.members.map((member) => ({ member, xp: getXp(state.allProgress[member.id] || []) })).sort((a, b) => b.xp - a.xp);
  return <Header eyebrow="TODAY'S MISSION" title={<>Keep the flame <em>alive.</em></>} copy="One meaningful objective is all it takes to keep momentum moving." action={<Link href={routeLesson(current.id)} className="primary-button">Open today’s quest <ArrowRight size={16} /></Link>}>
    <section className="dashboard-grid"><article className="today-card"><span className="card-kicker">DAY {String(current.number).padStart(2, "0")} · WEEK {current.week}</span><h2>{current.title}</h2><p>{current.concept}</p><div className="objective-peek">{objectives.slice(0, 3).map((text, index) => { const isDone = state.progress.some((entry) => entry.lesson_id === current.id && entry.objective_index === index && entry.completed); return <button key={text} onClick={() => changeProgress(current.id, index, !isDone)} className={isDone ? "done" : ""}><span>{isDone ? <Check size={13} /> : index + 1}</span>{text}</button>; })}</div><Link href={routeLesson(current.id)} className="text-link">See all 5 objectives <ChevronRight size={15} /></Link></article>
      <article className="xp-card"><div><span>YOUR LEVEL</span><strong>{getRank(xp).name}</strong><p>{xp} XP earned</p></div><div className="xp-orb"><b>{Math.min(100, Math.round(xp / (next ? next.xp : Math.max(xp, 1)) * 100))}%</b><small>to next</small></div>{next && <div className="xp-card-bottom">{next.xp - xp} XP until <strong>{next.name}</strong></div>}</article>
      <article className="streak-card-wide"><Flame fill="currentColor" /><div><span>CURRENT STREAK</span><strong>{getStreak(state.progress)} days</strong><p>Do one real thing today. That’s the deal.</p></div><Heatmap progress={state.progress} /></article></section>
    <section className="lower-grid"><section className="panel"><div className="panel-head"><div><span className="panel-label">CREW BOARD</span><h3>Everybody’s cooking</h3></div><Link href="/leaderboard" className="text-link">Full board <ArrowRight size={14} /></Link></div><div className="leader-list">{board.slice(0, 4).map((item, index) => <Link key={item.member.id} href={routeUser(item.member.public_name)} className="leader-row"><span className="place">{index + 1}</span><span className="avatar">{initials(item.member.public_name)}</span><strong>@{item.member.public_name}</strong><small>{getRank(item.xp).name}</small><b>{item.xp} XP</b></Link>)}</div></section>
      <section className="panel resolve-panel"><div className="panel-head"><div><span className="panel-label">RE-SOLVE QUEUE</span><h3>Bring it back</h3></div><span className="rotate-icon">↻</span></div>{dueResolves(state.progress).slice(0, 3).map((lesson) => <Link className="resolve-row" key={lesson.id} href={routeLesson(lesson.id)}><span>↻</span><div><strong>{lesson.title}</strong><small>Completed earlier · ready again</small></div><ChevronRight size={16} /></Link>)}{dueResolves(state.progress).length === 0 && <div className="empty-quiet">Nothing due today. A suspiciously peaceful queue.</div>}</section></section>
    <Badges progress={state.progress} projectCount={state.projects.filter((project) => project.user_id === state.profile.id).length} />
  </Header>;
}

function Badges({ progress, projectCount }: { progress: ProgressEntry[]; projectCount: number }) { return <section className="panel badge-panel"><div className="panel-head"><div><span className="panel-label">COLLECTIBLES</span><h3>Badges with bite</h3></div></div><div className="badge-grid">{getBadges(progress, projectCount).map((badge) => <div key={badge.name} className={"badge " + (badge.unlocked ? "unlocked" : "")}><span>{badge.icon}</span><div><strong>{badge.name}</strong><small>{badge.note}</small></div></div>)}</div></section>; }

function LessonPage({ lessonId, state, changeProgress, saveNote }: { lessonId: string; state: AppState; changeProgress: (lessonId: string, index: number, completed: boolean) => Promise<void>; saveNote: (note: LessonNote) => Promise<void> }) {
  const [, navigate] = useLocation(); const lesson = lessons.find((item) => item.id === lessonId) || lessons[0]; const objectives = objectiveText(lesson, state.profile.language); const saved = state.notes[lesson.id]; const [note, setNote] = useState<LessonNote>(saved || { lesson_id: lesson.id, takeaway: "", mistake: "", invariant: "" });
  useEffect(() => setNote(saved || { lesson_id: lesson.id, takeaway: "", mistake: "", invariant: "" }), [lesson.id, saved]);
  const done = state.progress.filter((entry) => entry.lesson_id === lesson.id && entry.completed).length; const previous = lessons[lesson.number - 2]; const next = lessons[lesson.number];
  return <Header eyebrow={"DAY " + String(lesson.number).padStart(2, "0") + " · " + lesson.weekTitle.toUpperCase()} title={<>{lesson.title}<em>.</em></>} copy={lesson.concept} action={<div className="lesson-progress"><strong>{done}/5</strong><span>objectives done</span></div>}><div className="lesson-layout"><article className="lesson-main">
    <section className="focus-block"><span>WHY THIS NOW</span><p>{lesson.focus}</p></section><div className="objective-list">{objectives.map((text, index) => { const complete = state.progress.some((entry) => entry.lesson_id === lesson.id && entry.objective_index === index && entry.completed); return <button key={text} className={"objective " + (complete ? "completed" : "")} onClick={() => changeProgress(lesson.id, index, !complete)}><span>{complete ? <Check size={16} /> : String(index + 1).padStart(2, "0")}</span><div><strong>{["Warm up", "Learn", "Build", "Practice", "Reflect"][index]}</strong><p>{text.replace(/^(Warm up|Learn|Build|Practice|Reflect): /, "")}</p></div><ChevronRight size={18} /></button>; })}</div>
    <div className="resource-callout"><div className="resource-icon"><GraduationCap size={20} /></div><div><span>FOCUSED RESOURCE</span><h3>{lesson.resource}</h3><p>Use it for the idea, then return here and make the algorithm earn it.</p></div><a className="small-button" href={lesson.resourceUrl} target="_blank" rel="noreferrer">Open <ExternalLink size={14} /></a></div>
    <a className="practice-callout" href={lesson.practiceUrl} target="_blank" rel="noreferrer"><Code2 size={19} /><div><span>THE PROBLEM</span><strong>{lesson.practice}</strong></div><ExternalLink size={16} /></a><div className="code-tip"><span>{state.profile.language.toUpperCase()} STARTER THOUGHT</span><code>{languageSnippets[state.profile.language]}</code></div>
    <section className="notes-card"><span className="panel-label">PRIVATE KITCHEN NOTES</span><h3>Capture the part you’ll forget.</h3><div className="note-fields"><label>Key takeaway<textarea value={note.takeaway} onChange={(e) => setNote({ ...note, takeaway: e.target.value })} placeholder="What clicked today?" /></label><label>Mistake / trap<textarea value={note.mistake} onChange={(e) => setNote({ ...note, mistake: e.target.value })} placeholder="What almost fooled you?" /></label><label>Invariant<textarea value={note.invariant} onChange={(e) => setNote({ ...note, invariant: e.target.value })} placeholder="What must stay true?" /></label></div><button className="dark-button compact" onClick={() => saveNote(note)}>Save private note</button></section>
    <nav className="lesson-nav">{previous ? <button onClick={() => navigate(routeLesson(previous.id))}>← {previous.title}</button> : <span />}{next ? <button onClick={() => navigate(routeLesson(next.id))}>Next: {next.title} →</button> : <Link href="/dashboard">Finish the roadmap <ArrowRight size={14} /></Link>}</nav>
  </article><aside className="lesson-aside"><div className="aside-card"><span>EDGE-CASE CHECK</span><p>{lesson.edgeCase}</p></div><div className="aside-card cream"><span>THE RECIPE</span><ol><li>Understand the state.</li><li>Trace a tiny example.</li><li>Write the simplest version.</li><li>Test boundaries.</li><li>Explain the invariant.</li></ol></div></aside></div></Header>;
}

function Roadmap({ state }: { state: AppState }) { const done = completedLessonIds(state.progress); return <Header eyebrow="THE FULL MENU" title={<>Seventy-two days.<br /><em>Zero random wandering.</em></>} copy="Every week is a skill layer. Finish it, remember it, then stack the next one."><div className="roadmap-grid">{Array.from({ length: 12 }, (_, index) => { const group = lessons.filter((lesson) => lesson.week === index + 1); const completed = group.filter((lesson) => done.has(lesson.id)).length; const target = group[Math.min(5, completed)]; return <article key={group[0].id} className={"week-card " + (completed === 6 ? "week-complete" : "")}><div><span>WEEK {String(index + 1).padStart(2, "0")}</span><b>{completed}/6</b></div><h2>{group[0].weekTitle}</h2><p>{group.map((lesson) => lesson.title).join(" · ")}</p><div className="week-track"><i style={{ width: completed / 6 * 100 + "%" }} /></div><Link href={routeLesson(target.id)}>{completed === 6 ? "Revisit week" : "Continue week"} <ArrowRight size={14} /></Link></article>; })}</div><section className="primer-panel"><div><span className="panel-label">NEW TO CODING?</span><h2>Start with the tiny prep kitchen.</h2><p>Not part of your XP total. Very much part of feeling ready.</p></div><div>{primer.map(([title, copy], index) => <div className="primer-row" key={title}><span>0{index + 1}</span><div><strong>{title}</strong><p>{copy}</p></div></div>)}</div></section></Header>; }

function Leaderboard({ state }: { state: AppState }) { const board = state.members.map((member) => ({ member, progress: state.allProgress[member.id] || [], xp: getXp(state.allProgress[member.id] || []) })).sort((a, b) => b.xp - a.xp); return <Header eyebrow="ONE BOARD. ALL THE HEAT." title={<>Who’s <em>cooking?</em></>} copy="XP comes from completed objectives and finished lessons. No weekly resets. No busywork."><section className="leaderboard-card">{board.map((item, index) => <Link href={routeUser(item.member.public_name)} className={"board-row " + (item.member.id === state.profile.id ? "you" : "")} key={item.member.id}><span className="rank-place">{index === 0 ? "♛" : String(index + 1).padStart(2, "0")}</span><span className="avatar large">{initials(item.member.public_name)}</span><div><strong>@{item.member.public_name}</strong><small>{getRank(item.xp).name} · {completedLessonIds(item.progress).size}/72 lessons</small></div><div className="board-bar"><i style={{ width: Math.min(100, item.xp / 55) + "%" }} /></div><b>{item.xp}<small> XP</small></b><ChevronRight size={18} /></Link>)}</section></Header>; }

function ProfilePage({ name, state }: { name: string; state: AppState }) { const profile = state.members.find((member) => member.public_name === name); if (!profile) return <NotFound />; const progress = state.allProgress[profile.id] || []; const xp = getXp(progress); const projects = state.projects.filter((project) => project.user_id === profile.id); return <Header eyebrow="CREW MEMBER" title={<>@{profile.public_name}<em>.</em></>} copy={profile.bio || "Currently cooking through the roadmap."}><section className="profile-hero"><Avatar profile={profile} className="profile-avatar" /><div><span>{getRank(xp).name}</span><h2>{xp} XP</h2><p>{getStreak(progress)} day streak · {completedLessonIds(progress).size}/72 lessons · {profile.language.toUpperCase()}</p></div><Heatmap progress={progress} /></section><Badges progress={progress} projectCount={projects.length} /><ProjectGrid projects={projects} members={state.members} /></Header>; }

function ProjectGrid({ projects, members }: { projects: Project[]; members: Profile[] }) { return <section className="projects-section"><div className="panel-head"><div><span className="panel-label">PROJECTS</span><h3>Things the crew has built</h3></div></div>{projects.length === 0 ? <div className="empty-projects">No projects plated yet. The first one could be yours.</div> : <div className="project-grid">{projects.map((project) => { const owner = members.find((member) => member.id === project.user_id); return <article className="project-card" key={project.id}>{project.cover_url ? <img src={project.cover_url} alt="" /> : <div className="project-cover"><Code2 size={35} /></div>}<div className="project-body"><span className="project-owner">@{owner ? owner.public_name : "cook"}</span><h3>{project.title}</h3><p>{project.description}</p><div className="tags">{project.tech.map((tag) => <span key={tag}>{tag}</span>)}</div><div className="project-links"><a href={project.github_url} target="_blank" rel="noreferrer"><Github size={15} />GitHub</a>{project.demo_url && <a href={project.demo_url} target="_blank" rel="noreferrer"><ExternalLink size={14} />Demo</a>}</div></div></article>; })}</div>}</section>; }

function ProjectsPage({ state, createProject, removeProject }: { state: AppState; createProject: (project: Omit<Project, "id" | "user_id" | "created_at">, file: File | null) => Promise<void>; removeProject: (id: string) => Promise<void> }) { const [open, setOpen] = useState(false); const own = state.projects.filter((project) => project.user_id === state.profile.id); return <Header eyebrow="SHOW YOUR WORK" title={<>Build it. <em>Plate it.</em></>} copy="Small DSA tools, visualizers, and experiments deserve a place on the table." action={<button className="primary-button" onClick={() => setOpen(true)}><Plus size={17} />Add a project</button>}><ProjectGrid projects={own} members={state.members} />{own.length > 0 && <div className="project-manage">{own.map((project) => <div key={project.id}><strong>{project.title}</strong><button onClick={() => removeProject(project.id)}>Remove</button></div>)}</div>}<AnimatePresence>{open && <ProjectForm close={() => setOpen(false)} save={async (project, file) => { await createProject(project, file); setOpen(false); }} />}</AnimatePresence></Header>; }

function ProjectForm({ close, save }: { close: () => void; save: (project: Omit<Project, "id" | "user_id" | "created_at">, file: File | null) => Promise<void> }) { const [title, setTitle] = useState(""); const [description, setDescription] = useState(""); const [tech, setTech] = useState(""); const [github, setGithub] = useState(""); const [demo, setDemo] = useState(""); const [file, setFile] = useState<File | null>(null); const [saving, setSaving] = useState(false); const submit = async (event: FormEvent) => { event.preventDefault(); setSaving(true); await save({ title, description, tech: tech.split(",").map((tag) => tag.trim()).filter(Boolean), github_url: github, demo_url: demo || null, cover_url: null }, file); setSaving(false); }; return <motion.div className="modal-backdrop" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}><motion.form className="project-form" onSubmit={submit} initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: 20 }}><button type="button" onClick={close} className="close-button"><X /></button><span className="panel-label">NEW PROJECT</span><h2>What did you cook up?</h2><label>Title<input required value={title} onChange={(e) => setTitle(e.target.value)} placeholder="Graph visualizer" /></label><label>Description<textarea required value={description} onChange={(e) => setDescription(e.target.value)} placeholder="A short, clear description." /></label><label>Technologies / topics<input value={tech} onChange={(e) => setTech(e.target.value)} placeholder="C++, graphs, Dijkstra" /></label><label>GitHub URL<input required type="url" value={github} onChange={(e) => setGithub(e.target.value)} placeholder="https://github.com/..." /></label><label>Demo URL <small>(optional)</small><input type="url" value={demo} onChange={(e) => setDemo(e.target.value)} placeholder="https://..." /></label><label>Cover image <small>(PNG, JPEG, or WebP · max 5 MB)</small><input type="file" accept="image/png,image/jpeg,image/webp" onChange={(e) => setFile(e.target.files ? e.target.files[0] || null : null)} /></label><button className="dark-button" disabled={saving}>{saving ? "Saving…" : "Publish project"}<ArrowRight size={16} /></button></motion.form></motion.div>; }

function Onboarding({ save }: { save: (value: { publicName: string; actualName: string; language: Language; bio: string }) => Promise<void> }) { const [publicName, setPublicName] = useState(""); const [actualName, setActualName] = useState(""); const [language, setLanguage] = useState<Language>("cpp"); const [bio, setBio] = useState(""); const [saving, setSaving] = useState(false); const submit = async (event: FormEvent) => { event.preventDefault(); setSaving(true); await save({ publicName: publicName.toLowerCase().replace(/[^a-z0-9_]/g, ""), actualName, language, bio }); setSaving(false); }; return <div className="onboarding"><Brand /><motion.form className="onboarding-card" onSubmit={submit} initial={{ opacity: 0, y: 14 }} animate={{ opacity: 1, y: 0 }}><span className="eyebrow dark"><Sparkles size={14} />FIRST, PLATE YOUR PROFILE</span><h1>Welcome to the kitchen.</h1><p>Your public handle is what the crew sees. Your actual name stays yours.</p><label>Public name<input required minLength={3} value={publicName} onChange={(e) => setPublicName(e.target.value)} placeholder="bytebloom" /><small>Letters, numbers, and underscores only.</small></label><label>Actual name <small>(private)</small><input required value={actualName} onChange={(e) => setActualName(e.target.value)} placeholder="Your name" /></label><label>Short bio <small>(optional)</small><input value={bio} onChange={(e) => setBio(e.target.value)} placeholder="What are you here to learn?" /></label><LanguageChoice language={language} setLanguage={setLanguage} /><button className="dark-button" disabled={saving}>{saving ? "Setting up…" : "Enter WeeeCooked"}<ArrowRight size={16} /></button></motion.form></div>; }

function LanguageChoice({ language, setLanguage }: { language: Language; setLanguage: (value: Language) => void }) { return <fieldset><legend>My primary language</legend><div className="language-options">{(["cpp", "java", "python"] as Language[]).map((item) => <button key={item} type="button" onClick={() => setLanguage(item)} className={language === item ? "selected" : ""}>{item === "cpp" ? "C++" : item === "java" ? "Java" : "Python"}</button>)}</div></fieldset>; }

function SettingsPage({ state, update }: { state: AppState; update: (profile: Profile, avatar: File | null) => Promise<void> }) { const [profile, setProfile] = useState(state.profile); const [avatar, setAvatar] = useState<File | null>(null); const [saving, setSaving] = useState(false); const submit = async (event: FormEvent) => { event.preventDefault(); setSaving(true); await update(profile, avatar); setSaving(false); }; return <Header eyebrow="SEASON TO TASTE" title={<>Your <em>settings.</em></>} copy="Your public handle travels through the crew. Your real name and email never do."><form className="settings-form" onSubmit={submit}><Avatar profile={profile} className="profile-avatar" /><label>Avatar <small>PNG, JPEG, or WebP · max 5 MB</small><input type="file" accept="image/png,image/jpeg,image/webp" onChange={(e) => setAvatar(e.target.files ? e.target.files[0] || null : null)} /></label><label>Public name<input value={profile.public_name} onChange={(e) => setProfile({ ...profile, public_name: e.target.value.toLowerCase().replace(/[^a-z0-9_]/g, "") })} /></label><label>Bio<textarea value={profile.bio || ""} onChange={(e) => setProfile({ ...profile, bio: e.target.value })} /></label><LanguageChoice language={profile.language} setLanguage={(language) => setProfile({ ...profile, language })} /><button className="dark-button" disabled={saving}>{saving ? "Saving…" : "Save changes"}<Check size={16} /></button></form></Header>; }

function AuthCallback({ refresh }: { refresh: () => Promise<void> }) { const [, navigate] = useLocation(); useEffect(() => { const run = async () => { if (!supabase) { navigate("/"); return; } const code = new URLSearchParams(window.location.search).get("code"); if (code) { const result = await supabase.auth.exchangeCodeForSession(code); if (result.error) toast.error("That sign-in link has expired. Please request a fresh one."); } await refresh(); navigate("/dashboard"); }; void run(); }, [navigate, refresh]); return <div className="loading-screen"><Brand /><span>Turning up the heat…</span></div>; }
function NotFound() { return <div className="not-found"><Brand /><h1>This pan is empty.</h1><p>That page does not exist—or it burnt down gracefully.</p><Link href="/dashboard" className="dark-button">Back to dashboard</Link></div>; }

function App() {
  const [location, navigate] = useLocation(); const [state, setState] = useState<AppState | null>(null); const [loading, setLoading] = useState(true); const [demo, setDemo] = useState(false);
  const load = async () => { if (!supabase) { setLoading(false); return; } const userResult = await supabase.auth.getUser(); const user = userResult.data.user; if (!user) { setState(null); setLoading(false); return; } const results = await Promise.all([supabase.from("profiles").select("*").eq("id", user.id).maybeSingle(), supabase.from("profiles").select("*"), supabase.from("objective_progress").select("lesson_id,objective_index,completed,completed_at,activity_date").eq("user_id", user.id), supabase.from("objective_progress").select("user_id,lesson_id,objective_index,completed,completed_at,activity_date"), supabase.from("lesson_notes").select("lesson_id,takeaway,mistake,invariant").eq("user_id", user.id), supabase.from("projects").select("*").order("created_at", { ascending: false })]); const profile = results[0].data; if (!profile) { setState(null); setLoading(false); navigate("/onboarding"); return; } const grouped: Record<string, ProgressEntry[]> = {}; (results[3].data || []).forEach((entry) => { if (!grouped[entry.user_id]) grouped[entry.user_id] = []; grouped[entry.user_id].push(entry); }); const notes: Record<string, LessonNote> = {}; (results[4].data || []).forEach((note) => { notes[note.lesson_id] = note; }); setState({ profile, members: results[1].data || [profile], progress: results[2].data || [], allProgress: grouped, notes, projects: results[5].data || [] }); setLoading(false); };
  useEffect(() => { void load(); const watcher = supabase ? supabase.auth.onAuthStateChange(() => { void load(); }) : null; return () => { if (watcher) watcher.data.subscription.unsubscribe(); }; }, []);
  const openDemo = () => { setDemo(true); setState({ profile: demoProfile, members: demoMembers, progress: demoProgress, allProgress: demoMemberProgress, notes: {}, projects: demoProjects }); navigate("/dashboard"); };
  const finishOnboarding = async (value: { publicName: string; actualName: string; language: Language; bio: string }) => { if (!supabase) { openDemo(); return; } const user = (await supabase.auth.getUser()).data.user; if (!user) return; const profileResult = await supabase.from("profiles").upsert({ id: user.id, public_name: value.publicName, language: value.language, bio: value.bio || null }); if (profileResult.error) { toast.error(profileResult.error.message.includes("unique") ? "That public name is already taken." : profileResult.error.message); return; } await supabase.from("private_profiles").upsert({ user_id: user.id, actual_name: value.actualName }); await load(); navigate("/dashboard"); };
  const changeProgress = async (lessonId: string, index: number, completed: boolean) => { if (!state) return; const entry: ProgressEntry = { lesson_id: lessonId, objective_index: index, completed, completed_at: completed ? new Date().toISOString() : null, activity_date: completed ? toDateKey() : null }; if (demo) { const progress = state.progress.filter((item) => item.lesson_id !== lessonId || item.objective_index !== index); if (completed) progress.push(entry); setState({ ...state, progress, allProgress: { ...state.allProgress, [state.profile.id]: progress } }); if (completed) toast.success("+10 XP — nice work."); return; } if (!supabase) return; const user = (await supabase.auth.getUser()).data.user; if (!user) return; const result = await supabase.from("objective_progress").upsert({ user_id: user.id, ...entry }, { onConflict: "user_id,lesson_id,objective_index" }); if (result.error) toast.error(result.error.message); else { await load(); if (completed) toast.success("+10 XP — nice work."); } };
  const saveNote = async (note: LessonNote) => { if (!state) return; if (demo) { setState({ ...state, notes: { ...state.notes, [note.lesson_id]: note } }); toast.success("Private note saved."); return; } if (!supabase) return; const user = (await supabase.auth.getUser()).data.user; if (!user) return; const result = await supabase.from("lesson_notes").upsert({ user_id: user.id, ...note }, { onConflict: "user_id,lesson_id" }); if (result.error) toast.error(result.error.message); else { await load(); toast.success("Private note saved."); } };
  const updateProfile = async (profile: Profile, avatar: File | null) => { if (!state) return; if (avatar && (!/image\/(png|jpeg|webp)/.test(avatar.type) || avatar.size > 5 * 1024 * 1024)) { toast.error("Use a PNG, JPEG, or WebP image smaller than 5 MB."); return; } let avatarUrl = profile.avatar_url; if (demo && avatar) avatarUrl = URL.createObjectURL(avatar); if (!demo && supabase && avatar) { const path = profile.id + "/avatar-" + crypto.randomUUID() + "." + (avatar.name.split(".").pop() || "png"); const uploaded = await supabase.storage.from("avatars").upload(path, avatar); if (uploaded.error) { toast.error(uploaded.error.message); return; } avatarUrl = supabase.storage.from("avatars").getPublicUrl(path).data.publicUrl; } const value = { ...profile, avatar_url: avatarUrl }; if (demo) { setState({ ...state, profile: value, members: state.members.map((member) => member.id === value.id ? value : member) }); toast.success("Settings saved."); return; } if (!supabase) return; const result = await supabase.from("profiles").update({ public_name: value.public_name, bio: value.bio, language: value.language, avatar_url: value.avatar_url }).eq("id", value.id); if (result.error) toast.error(result.error.message); else { await load(); toast.success("Settings saved."); } };
  const createProject = async (project: Omit<Project, "id" | "user_id" | "created_at">, file: File | null) => { if (!state) return; if (file && (!/image\/(png|jpeg|webp)/.test(file.type) || file.size > 5 * 1024 * 1024)) { toast.error("Use a PNG, JPEG, or WebP image smaller than 5 MB."); return; } let coverUrl = project.cover_url; if (!demo && supabase && file) { const path = state.profile.id + "/" + crypto.randomUUID() + "-" + file.name.replace(/[^a-zA-Z0-9.\-_]/g, "-"); const upload = await supabase.storage.from("project-covers").upload(path, file); if (upload.error) { toast.error(upload.error.message); return; } coverUrl = supabase.storage.from("project-covers").getPublicUrl(path).data.publicUrl; } const value = { ...project, cover_url: coverUrl }; if (demo) { setState({ ...state, projects: [{ ...value, id: crypto.randomUUID(), user_id: state.profile.id, created_at: new Date().toISOString() }, ...state.projects] }); toast.success("Project plated."); return; } if (!supabase) return; const user = (await supabase.auth.getUser()).data.user; if (!user) return; const result = await supabase.from("projects").insert({ user_id: user.id, ...value }); if (result.error) toast.error(result.error.message); else { await load(); toast.success("Project plated."); } };
  const removeProject = async (id: string) => { if (!state || !window.confirm("Remove this project from WeeeCooked?")) return; if (demo) { setState({ ...state, projects: state.projects.filter((project) => project.id !== id) }); return; } if (!supabase) return; const result = await supabase.from("projects").delete().eq("id", id); if (result.error) toast.error(result.error.message); else { await load(); toast.success("Project removed."); } };
  const signOut = async () => { if (demo) { setDemo(false); setState(null); navigate("/"); return; } if (supabase) await supabase.auth.signOut(); setState(null); navigate("/"); };
  if (loading && isSupabaseConfigured) return <div className="loading-screen"><Brand /><span>Heating up the kitchen…</span></div>;
  const hasAuthCode = typeof window !== "undefined" && new URLSearchParams(window.location.search).has("code");
  if (location === "/auth/callback" || hasAuthCode) return <AuthCallback refresh={load} />;
  if (location === "/onboarding") return <Onboarding save={finishOnboarding} />;
  if (!state) return <Landing openDemo={openDemo} />;
  return <Shell state={state} demo={demo} signOut={signOut}><Switch><Route path="/dashboard"><Dashboard state={state} changeProgress={changeProgress} /></Route><Route path="/roadmap"><Roadmap state={state} /></Route><Route path="/leaderboard"><Leaderboard state={state} /></Route><Route path="/learn/:id">{(params) => <LessonPage lessonId={params.id} state={state} changeProgress={changeProgress} saveNote={saveNote} />}</Route><Route path="/u/:name">{(params) => <ProfilePage name={params.name} state={state} />}</Route><Route path="/projects"><ProjectsPage state={state} createProject={createProject} removeProject={removeProject} /></Route><Route path="/settings"><SettingsPage state={state} update={updateProfile} /></Route><Route><NotFound /></Route></Switch></Shell>;
}

export default function Root() { return <Router base={import.meta.env.BASE_URL}><App /><Toaster position="top-right" richColors /></Router>; }
